### PR TITLE
Return exit code 1 when build fails for test

### LINKED ISSUE #1512: When running tests, compile error results in error code 0
**Version(s)**
0.1.16

**Describe the bug**
If I run `scala-cli test` and the code does not compile, the error messages get displayed but the command returns 0, i.e. success. This is problematic for example in CI pipelines.

**To Reproduce**
1. Create an empty folder and in it create `tests/SomeTest.scala`:
```Scala
//> using lib "org.scalameta::munit::0.7.29"

class  SomeTest extends munit.FunSuite:
	test("failig") {
		val s: String = 1
		assert(true == true)
	}
```
2. run `scala-cli test . && echo "tests OK" || echo "tests failed"`
3. This results in
```
[error] ./test/SomeTest.scala:5:19: Found:    (1 : Int)
[error] Required: String
[error] 
[error] The following import might make progress towards fixing the problem:
[error] 
[error]   import munit.Clue.generate
[error] 
[error] 		val s: String = 1
[error]                   ^
Error compiling project (test, Scala 3.2.0, JVM)
tests OK
```
**Expected behaviour**
The error code should be non-zero, and thus the output of the above command should be
```
[error] ./test/SomeTest.scala:5:19: Found:    (1 : Int)
[error] Required: String
[error] 
[error] The following import might make progress towards fixing the problem:
[error] 
[error]   import munit.Clue.generate
[error] 
[error] 		val s: String = 1
[error]                   ^
Error compiling project (test, Scala 3.2.0, JVM)
tests failed
```

### PR DESCRIPTION
**Pull request by lwronski**
Fixes #1512

### CODE REVIEW

File: modules/build/src/main/scala/scala/build/Builds.scala [hunk 1]
```diff
@@ -14,6 +14,7 @@ final case class Builds(
     }
   def get(scope: Scope): Option[Build] =
     builds.find(_.scope == scope)
+  def isFail: Boolean = !builds.forall(_.success)
```
Comment (Gedochao) [inline modules/build/src/main/scala/scala/build/Builds.scala]:
```suggestion
  def anyFailed: Boolean = !builds.forall(_.success)
```
also, shouldn't we check all the builds here?
if so, then:
```suggestion
  def anyFailed: Boolean = !all.forall(_.success)
```

Comment (lwronski) [reply modules/build/src/main/scala/scala/build/Builds.scala]: good catch! thanks

**Review by Gedochao — APPROVED** [review]
