### PR TITLE
Pass `javaHome` to Bloop

### LINKED ISSUE #2663: Platform should be set when non default JVM is used.
**Version(s)**
1.1.1

**Describe the bug**
Currently, if the user specifies JDK 11 as the JVM to use as in:

The platform section used for Bloop should show that, but it doesn't:
`"platform": { "name": "jvm", "config": { "options": [] }, "mainClass": [] },`

This means when running the wrong JVM will be used, the one Bloop runs on.

**To Reproduce**

```
//> using scala 3.3.1
//> using jvm adopt:1.11

@main
def main = 
    println(s"Hello java ${sys.props("java.home")}!")

```

prints:
`Hello java /usr/lib/jvm/graal17!` in my case, since I have graal17.

**Expected behaviour**
Prints:

`Hello java <coursier-java-path>!`

### PR DESCRIPTION
**Pull request by kasiaMarek**
resolves: https://github.com/VirtusLab/scala-cli/issues/2663

### CODE REVIEW

**Review by Gedochao — APPROVED** [review]
LGTM

File: modules/integration/src/test/scala/scala/cli/integration/BloopTests.scala [hunk 1]
```diff
@@ -1,6 +1,7 @@
 package scala.cli.integration
 
 import com.eed3si9n.expecty.Expecty.expect
+import os.Pipe
```
Comment (Gedochao) [inline modules/integration/src/test/scala/scala/cli/integration/BloopTests.scala]: NIT don't import stuff from the `os.*` package, we generally use things from that package directly
