### PR TITLE
Fix - use resourcesDir in package command

### LINKED ISSUE #509: ScalaCLI resourceDir doesn't work with package
Thanks for @teigen detailed description of the problem
https://gist.github.com/teigen/16059fa6413a023d939d7ed35925a613

> A little project demonstrating problems with resourceDir.
> ```
> 16:28 λ tree
> .
> ├── Test.scala
> └── resources
>     └── data.txt
> 
> 1 directory, 2 files
> ```
> ```
> 16:28 λ cat Test.scala 
> // using scala 3.0.2
> // using resourceDir "./resources"
> @main def main = 
>   println(Thread.currentThread().getContextClassLoader.getResource("data.txt"))
> ```
> ```
> 16:28 λ cat resources/data.txt 
> Hello!
> ```
> Running it works great :-)
> ```
> 16:29 λ scala-cli run .
> Compiling project (Scala 3.0.2, JVM)
> Compiled project (Scala 3.0.2, JVM)
> file:/Users/jteigen/Development/cli-resource/resources/data.txt
> ```
> ```
> 16:29 λ scala-cli package .
> Compiling project (Scala 3.0.2, JVM)
> Compiled project (Scala 3.0.2, JVM)
> Wrote app, run it with
>   ./app
> ```
> ```
> 16:29 λ ./app
> null
> ```
> Running the packaged version does not :-(
> ```
> 16:29 λ jar xf app coursier/bootstrap/launcher/jars/app-content.jar
> ```
> Inspecting the packaged jar-file shows the file is missing
> ```
> 16:30 λ jar tf coursier/bootstrap/launcher/jars/app-content.jar 
> META-INF/MANIFEST.MF
> Test$package.tasty
> main.tasty
> main.class
> Test$package$.class
> Test$package.class
> ```
> Lets export to sbt!
> ```
> 16:30 λ scala-cli export --sbt .
> ```
> ```
> 16:30 λ cd dest
> ```
> ```
> 16:30 λ cat build.sbt 
> 
> // Scala CLI doesn't distinguish main and test sources for now.
> Test / sources ++= (Compile / sources).value
> 
> scalaVersion := "3.0.2"
> 
> 
> 
> 
> 
> 
> Compile / unmanagedClasspath ++= Seq(file("/Users/jteigen/Development/cli-resource/resources"))
> Runtime / unmanagedClasspath ++= Seq(file("/Users/jteigen/Development/cli-resource/resources"))
> 
> 
> 
> 
> ```
> ```
> 16:30 λ sbt run
> [info] welcome to sbt 1.5.5 (Homebrew Java 11.0.12)
> [info] loading global plugins from /Users/jteigen/.sbt/1.0/plugins
> [info] loading project definition from /Users/jteigen/Development/cli-resource/dest/project
> [info] loading settings for project dest from build.sbt ...
> [info] set current project to dest (in build file:/Users/jteigen/Development/cli-resource/dest/)
> [info] compiling 1 Scala source to /Users/jteigen/Development/cli-resource/dest/target/scala-3.0.2/classes ...
> [info] running main 
> file:/Users/jteigen/Development/cli-resource/dest/target/bg-jobs/sbt_a8cc4955/target/0020f180/a4662cdd/resources/data.txt
> [success] Total time: 4 s, completed Dec 17, 2021, 4:30:56 PM
> ```
> Running it works. But just like with `scala-cli run` it find the file on the filesystem, not in the jar.
> Inspecting the jar reveals why
> ```
> 16:30 λ jar tf target/scala-3.0.2/dest_3-0.1.0-SNAPSHOT.jar 
> META-INF/MANIFEST.MF
> Test$package$.class
> Test$package.class
> Test$package.tasty
> main.class
> main.tasty
> ```
> If we make some minor adjustments to `build.sbt` to match what I *thought* `resourceDir` did
> (https://www.scala-sbt.org/1.x/docs/Howto-Customizing-Paths.html#Add+an+additional+resource+directory)
> ```
> 16:31 λ vim build.sbt 
> ```
> ```
> 16:31 λ cat build.sbt 
> 
> // Scala CLI doesn't distinguish main and test sources for now.
> Test / sources ++= (Compile / sources).value
> 
> scalaVersion := "3.0.2"
> 
> Compile / unmanagedResourceDirectories ++= Seq(file("/Users/jteigen/Development/cli-resource/resources"))
> ```
> Running shows that the resource file is now resolved from the jar-file, not the filesystem.
> ```
> 16:32 λ sbt run
> [info] welcome to sbt 1.5.5 (Homebrew Java 11.0.12)
> [info] loading global plugins from /Users/jteigen/.sbt/1.0/plugins
> [info] loading project definition from /Users/jteigen/Development/cli-resource/dest/project
> [info] loading settings for project dest from build.sbt ...
> [info] set current project to dest (in build file:/Users/jteigen/Development/cli-resource/dest/)
> [info] running main 
> jar:file:/Users/jteigen/Development/cli-resource/dest/target/bg-jobs/sbt_c7561821/job-1/target/4ed69241/c326b934/dest_3-0.1.0-SNAPSHOT.jar!/data.txt
> [success] Total time: 1 s, completed Dec 17, 2021, 4:32:14 PM
> ```
> As our jar file contains the resource-file
> ```
> 16:32 λ jar tf target/scala-3.0.2/dest_3-0.1.0-SNAPSHOT.jar 
> META-INF/MANIFEST.MF
> Test$package$.class
> Test$package.class
> Test$package.tasty
> data.txt
> main.class
> main.tasty
> ```

### PR DESCRIPTION
**Pull request by lwronski**
Due to a bug in the bloop [#1631](https://github.com/scalacenter/bloop/issues/1631), scala-cli have to copy resources to `classesDir`. 

I also added exporting resources as `unmanagedResourceDirectories` in Sbt.

### CODE REVIEW

File: modules/build/src/main/scala/scala/build/Build.scala [hunk 1]
```diff
@@ -256,9 +256,34 @@ object Build {
     val (testBuild, extraTestBuilds) =
       value(buildScope(Scope.Test, Some(mainBuild), Some(extraBuilds)))
 
+    copyResourceToClassesDir(mainBuild)
```
Comment (alexarchambault) [inline modules/build/src/main/scala/scala/build/Build.scala]: Maybe move this one right after `val (mainBuild, extraBuilds) = …` (but before `val (testBuild, extraTestBuilds) = …`), so that these are copied whenever the main build is successful.

File: modules/build/src/main/scala/scala/build/Build.scala [hunk 2]
```diff
@@ -256,9 +256,34 @@ object Build {
...
+      } yield {
+        val destPath = b.output / relativeResourcePath
+        os.copy(
+          resourceFilePath,
+          destPath,
+          replaceExisting = true,
+          createFolders = true
+        )
+      }
+    case _ => ()
```
Comment (alexarchambault) [inline modules/build/src/main/scala/scala/build/Build.scala]: NIT
```suggestion
    case _ =>
```

File: modules/build/src/main/scala/scala/build/Build.scala [hunk 3]
```diff
@@ -256,9 +256,34 @@ object Build {
...
+    case b: Build.Successful =>
+      for {
+        resourceDirPath  <- b.sources.resourceDirs
+        resourceFilePath <- os.walk(resourceDirPath)
+        if os.isFile(resourceFilePath)
+        relativeResourcePath = resourceFilePath.relativeTo(resourceDirPath)
+        if !relativeResourcePath.toString.startsWith(
+          ".scala"
+        ) // dismiss files generated by scala-cli
+      } yield {
```
Comment (alexarchambault) [inline modules/build/src/main/scala/scala/build/Build.scala]: No need of the yield here, as this method returns a `Unit` IIUC.
```suggestion
      } {
```

File: modules/build/src/main/scala/scala/build/Build.scala [hunk 4]
```diff
@@ -256,9 +256,34 @@ object Build {
...
+  private def copyResourceToClassesDir(build: Build) = build match {
+    case b: Build.Successful =>
+      for {
+        resourceDirPath  <- b.sources.resourceDirs
+        resourceFilePath <- os.walk(resourceDirPath)
+        if os.isFile(resourceFilePath)
+        relativeResourcePath = resourceFilePath.relativeTo(resourceDirPath)
+        if !relativeResourcePath.toString.startsWith(
+          ".scala"
+        ) // dismiss files generated by scala-cli
```
Comment (alexarchambault) [inline modules/build/src/main/scala/scala/build/Build.scala]: ?
```suggestion
        // dismiss files generated by scala-cli
        if !relativeResourcePath.startsWith(os.rel / ".scala")
```

File: modules/build/src/main/scala/scala/build/preprocessing/directives/UsingResourcesDirectiveHandler.scala [hunk 5]
```diff
@@ -26,19 +27,28 @@ case object UsingResourcesDirectiveHandler extends UsingDirectiveHandler {
...
         )
       )),
       Seq.empty
     )
   }
+  def validatePath(path: os.Path): Either[BuildException, os.Path] =
+    if (os.exists(path))
+      Right(path)
+    else
+      Left(new NoResourcePathFoundError(path))
```
Comment (alexarchambault) [inline modules/build/src/main/scala/scala/build/preprocessing/directives/UsingResourcesDirectiveHandler.scala]: For later: maybe this could be reported as a warning instead.

File: modules/build/src/main/scala/scala/build/preprocessing/directives/UsingResourcesDirectiveHandler.scala [hunk 6]
```diff
@@ -26,19 +27,28 @@ case object UsingResourcesDirectiveHandler extends UsingDirectiveHandler {
   ): Either[BuildException, ProcessedUsingDirective] = either {
     val (virtualRootOpt, rootOpt) = Directive.osRootResource(cwd)
     val paths                     = DirectiveUtil.stringValues(directive.values, path, cwd)
-    val paths0                    = rootOpt.map(root => paths.map(_._1).map(os.Path(_, root)))
+    val paths0: Seq[os.Path] = value {
+      rootOpt.map(root => paths.map(_._1).map(os.Path(_, root))).toList.flatten
+        .map(validatePath)
+        .sequence.left.map(_.head)
```
Comment (alexarchambault) [inline modules/build/src/main/scala/scala/build/preprocessing/directives/UsingResourcesDirectiveHandler.scala]: This discard errors (only keeps the first one). This shouldn't discard them:
```suggestion
        .sequence
        .left.map(CompositeBuildException(_))
```

File: modules/build/src/main/scala/scala/build/preprocessing/directives/UsingResourcesDirectiveHandler.scala [hunk 7]
```diff
@@ -26,19 +27,28 @@ case object UsingResourcesDirectiveHandler extends UsingDirectiveHandler {
   ): Either[BuildException, ProcessedUsingDirective] = either {
     val (virtualRootOpt, rootOpt) = Directive.osRootResource(cwd)
     val paths                     = DirectiveUtil.stringValues(directive.values, path, cwd)
-    val paths0                    = rootOpt.map(root => paths.map(_._1).map(os.Path(_, root)))
+    val paths0: Seq[os.Path] = value {
+      rootOpt.map(root => paths.map(_._1).map(os.Path(_, root))).toList.flatten
```
Comment (alexarchambault) [inline modules/build/src/main/scala/scala/build/preprocessing/directives/UsingResourcesDirectiveHandler.scala]: NIT
```suggestion
      rootOpt.toList.flatMap(root => paths.map(_._1).map(os.Path(_, root)))
```

File: modules/cli/src/main/scala/scala/cli/commands/SharedOptions.scala [hunk 8]
```diff
@@ -222,6 +222,14 @@ final case class SharedOptions(
     }
     val resourceInputs = resourceDirs
       .map(os.Path(_, Os.pwd))
+      .map { path =>
+        if (os.exists(path))
+          path
+        else {
+          System.err.println(s"Provided resource directory path doesn't exist: $path")
+          sys.exit(1)
```
Comment (alexarchambault) [inline modules/cli/src/main/scala/scala/cli/commands/SharedOptions.scala]: Do we really want to do that? This should be reported as an error later on by the `NoResourcePathFoundError` above, right?

File: modules/integration/src/test/scala/scala/cli/integration/PackageTestDefinitions.scala [hunk 9]
```diff
@@ -72,6 +72,96 @@ abstract class PackageTestDefinitions(val scalaVersionOpt: Option[String])
...
+      )
+    )
+    inputs.fromRoot { root =>
+      os.proc(TestUtil.cli, "package", extraOptions, ".", "-o", outputLib, "--library").call(
+        cwd = root,
+        stdin = os.Inherit,
+        stdout = os.Inherit
+      )
+
+      val output = os.proc("jar", "tf", root / outputLib).call(cwd = root).out.text().trim
```
Comment (alexarchambault) [inline modules/integration/src/test/scala/scala/cli/integration/PackageTestDefinitions.scala]: The output file could be inspected by `java.util.zip.ZipFile` instead. Something like
```scala
import java.util.zip.ZipFile
val zf = new ZipFile((root / outputLib).toIO)
val entry = zf.getEntry(resourceFile)
expect(entry != null)
```

File: modules/cli/src/main/scala/scala/cli/commands/SharedOptions.scala (hunk 8 above)
Comment (lwronski) [reply modules/cli/src/main/scala/scala/cli/commands/SharedOptions.scala]: It will not be reported as the error handling above only applies to directives.

File: modules/build/src/main/scala/scala/build/Build.scala (hunk 4 above)
Comment (lwronski) [reply modules/build/src/main/scala/scala/build/Build.scala]: I want to avoid included files generated by scala-cli to jars. For example, if I run `scala-cli package Hello.scala`
```
head Hello.scala
// using resourceDir "."
```
all `.scala` files would appear in the jar in this case

File: modules/build/src/main/scala/scala/build/CrossSources.scala [hunk 10]
```diff
@@ -142,19 +143,7 @@ object CrossSources {
...
-            preprocessors.iterator
-              .flatMap(p => p.preprocess(elem).iterator)
-              .take(1).toList.headOption
-              .getOrElse(Right(Nil))
-              .map(_.flatMap(_.mainClassOpt.toSeq).headOption)
-        }
-        .sequence
-        .map(_.flatten)
-    }
+    val mainClassOpt = preprocessedSources.flatMap(_.mainClassOpt.toSeq).headOption
```
Comment (lwronski) [inline modules/build/src/main/scala/scala/build/CrossSources.scala]: It wasn't' necessary to run directive processing for mainClass because it was done before in `preprocessedSources`. 

I had a problem that the warning logging for the main class was printed twice.

File: modules/build/src/main/scala/scala/build/Build.scala (hunk 4 above)
Comment (alexarchambault) [reply modules/build/src/main/scala/scala/build/Build.scala]: I think they wouldn't even with my suggested changes (which make it ignore the `.scala` directory right under `resourceDirPath`).
