### PR TITLE
fix: start bloop with jvm version from using directives for JVMs > 17

### LINKED ISSUE #2969: `//> using jvm` isn't respected for JVMs >17
**Version(s)**
v1.3.2

**Describe the bug**
Bloop JVM seems to only respect the `--jvm` command line flag, while completely ignoring the `//> using jvm` directive.

**To Reproduce**
Stop Bloop if it's running
```bash
scala-cli bloop exit --power
# Stopped Bloop server.
```

Try running the following code as `Simple.java`:
```java
// Simple.java
//> using jvm 22
//> using javacOpt --enable-preview -Xlint:preview
//> using javaOpt --enable-preview
//> using mainClass Simple

void main() {
    System.out.println("Hello from Java 22");
}
```

```bash
scala-cli Simple.java
# Starting compilation server
# [warn]  JVM that is hosting bloop is older than the requested runtime. Please restart the Build Server from your IDE.
# [warn] Or run the command `bloop exit`, and then use `--jvm` flag to request a sufficient JVM version.
# [warn] COMMAND_LINE
# [warn] [current bloop jvm] /Users/pchabelski/Library/Caches/Coursier/arc/https/github.com/adoptium/temurin17-binaries/releases/download/jdk-17%252B35/OpenJDK17-jdk_aarch64_mac_hotspot_17_35.tar.gz/jdk-17+35/Contents/Home
```

Despite `bloop` being killed and `//> using jvm 22` in the code, Scala CLI still asks for the `--jvm` flag to be passed to run this code.

Running with `--jvm 22` works fine:
```bash
# scala-cli Simple.java --jvm 22
# Starting compilation server
# Compiling project (Java)
# Annotation processing is enabled because one or more processors were found
#   on the class path. A future release of javac may disable annotation processing
#   unless at least one processor is specified by name (-processor), or a search
#   path is specified (--processor-path, --processor-module-path), or annotation
#   processing is enabled explicitly (-proc:only, -proc:full).
#   Use -Xlint:-options to suppress this message.
#   Use -proc:none to disable annotation processing.
# [warn] ./Simple.java:7:1
# [warn] implicitly declared classes are a preview feature and may be removed in a future release.
# [warn] void main() {
# [warn] ^
# Warning: Error reading API from class file: Simple : java.lang.UnsupportedClassVersionError: Preview features are not # enabled for Simple (class file version 66.65535). Try running with '--enable-preview'
# Compiled project (Java)
# Hello from Java 22
```

**Expected behaviour**
I'd expect the `--jvm` command line option and `//> using jvm` directive to be interchangeable here.

### PR DESCRIPTION
**Pull request by kasiaMarek**
resolves: https://github.com/VirtusLab/scala-cli/issues/2969

### CODE REVIEW

File: modules/integration/src/test/scala/scala/cli/integration/BloopTests.scala [hunk 1]
```diff
@@ -168,4 +168,25 @@ class BloopTests extends ScalaCliSuite {
...
+            |//> using javacOpt --enable-preview -Xlint:preview
+            |//> using javaOpt --enable-preview
+            |//> using mainClass Simple
+            |
+            |void main() {
+            |    System.out.println("$hello");
+            |}""".stripMargin
+    )
+    inputs.fromRoot { root =>
+      val res = runScalaCli("Simple.java").call(cwd = root)
```
Comment (Gedochao) [inline modules/integration/src/test/scala/scala/cli/integration/BloopTests.scala:188]: I'd first explicitly force Bloop to run on Java 17 here, to make sure nothing else is picked from the environment, some other test or w/e. And only then check if the directive ups Bloop to 21.

**Review by Gedochao — APPROVED** [review]
LGTM
