### PR TITLE
using directives correctly parsing Numeric and Boolean values

### LINKED ISSUE #561: Properly handle using directives in scala-cli
As for now, our integration with using directives is not perfect namely:
- we should properly handle directives other then string (numerical and binary) in all our process (probably enforce it within API somehow). Where it makes sense we should support it (e.g. numerical for Scala version) and where not we should fail  with proper error message
- we should report proper errors for directives that does not parse (properly handle reporter from using direcectives)
- using directives should print proper positions

### PR DESCRIPTION
**Pull request by ghost**
resolves https://github.com/VirtusLab/scala-cli/issues/561

### CODE REVIEW

File: modules/build/src/main/scala/scala/build/preprocessing/directives/UsingScalaVersionDirectiveHandler.scala [hunk 1]
```diff
@@ -17,24 +23,51 @@ case object UsingScalaVersionDirectiveHandler extends UsingDirectiveHandler {
...
     path: Either[String, os.Path],
     cwd: ScopePath,
     logger: Logger
   ): Either[BuildException, ProcessedUsingDirective] = {
-    val values        = directive.values
-    val scalaVersions = DirectiveUtil.stringValues(values, path, cwd)
-    if (scalaVersions.isEmpty)
-      Left(new NoScalaVersionProvidedError)
+    val numOfValues = directive.values.length
+    if (numOfValues > 1)
```
Comment (romanowski) [inline modules/build/src/main/scala/scala/build/preprocessing/directives/UsingScalaVersionDirectiveHandler.scala]: We will use `// using scala 3.1 2.13 2.12` for cross compilation of libraries if I am not mistaken

cc @alexarchambault

Comment (ghost) [reply modules/build/src/main/scala/scala/build/preprocessing/directives/UsingScalaVersionDirectiveHandler.scala]: using directives syntax cannot detect multiple values that are not comma separated! So it detects:
`//> using scala 3.1, 2.13, 2.12`

**Comment by ghost** [comment]
This is going to create conflicts with PR #749 
So PR #749 needs to get merged first. Then this branch has to get rebased on that and incorporate the changes by resolving conflicts before getting merged!

**Comment by jchyb** [comment]
I think #749 can wait. It's relatively low priority - I did some very simple changes there and then perhaps went overboard with the refactorings

**Comment by ghost** [comment]
@jchyb is it fine if I bring your changes here and directly apply it?

**Comment by jchyb** [comment]
Sure!

File: modules/directives/src/main/scala/scala/build/directives/ScopedValue.scala [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+import scala.build.Positioned
+import scala.build.preprocessing.ScopePath
+
+case class ScopedValue[T <: Value[_]](
+  positioned: Positioned[String],
+  maybeScopePath: Option[ScopePath] = None
+) {
+//  override def toString = s"$positioned of type ${kind(this)}${maybeScopePath.map { scopePath =>
+//      s" with scope path $scopePath"
+//    }.getOrElse("")}"
```
Comment (romanowski) [inline modules/directives/src/main/scala/scala/build/directives/ScopedValue.scala]:
```suggestion

```

Comment (romanowski) [reply modules/directives/src/main/scala/scala/build/directives/ScopedValue.scala]: commented out code

File: modules/directives/src/main/scala/scala/build/directives/UsingDirectiveValueNumberBounds.scala [hunk 3]
```diff
@@ -0,0 +1,22 @@
+package scala.build.preprocessing.directives
+
+case class UsingDirectiveValueNumberBounds(
```
Comment (romanowski) [inline modules/directives/src/main/scala/scala/build/directives/UsingDirectiveValueNumberBounds.scala:3]: It sees that we only have 3 case used:
 - AtMostOne: `UsingDirectiveValueNumberBounds(0,1)`
 - One :  `UsingDirectiveValueNumberBounds(1,1)`
 - AtLeastOne: ` `UsingDirectiveValueNumberBounds(1,MaxInt)`
 
I from the perspective of readablity of error messages I think having a dedicated message for each such case would be more easy to understand then general message, especially if it contains `MaxInt`

File: modules/directives/src/main/scala/scala/build/directives/UsingDirectiveValueNumberBounds.scala [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+//  type LowerBoundNumberOfExpectedValues = Value
+//  val AT_LEAST_ONE = Value(1)
+//  val NO           = Value(0)
+//}
+//
+//object UpperBoundNumberOfExpectedValues extends Enumeration {
+//  type UpperBoundNumberOfExpectedValues = Value
+//  val AT_MOST_ONE = Value(1)
+//  val MULTIPLE    = Value(Int.MaxValue)
+//}
```
Comment (romanowski) [inline modules/directives/src/main/scala/scala/build/directives/UsingDirectiveValueNumberBounds.scala]:
```suggestion
```

File: modules/directives/src/main/scala/scala/build/errors/UsingDirectiveExpectationError.scala [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+  maybePath: Either[String, os.Path],
+  key: String,
+  expectedTypes: Set[UsingDirectiveValueKind],
+  providedPositionedTypesContainer: GroupedScopedValuesContainer,
+  hint: String = ""
+) extends UsingDirectiveExpectationError(
+      maybePath,
+      key,
+      s"""${expectedTypes.mkString(
+          ",or "
```
Comment (romanowski) [inline modules/directives/src/main/scala/scala/build/errors/UsingDirectiveExpectationError.scala]:
```suggestion
          ", or "
```

File: modules/directives/src/main/scala/scala/build/errors/WrongJavaHomePathError.scala [hunk 6]
```diff
@@ -0,0 +1,7 @@
+package scala.build.errors
+
+class WrongJavaHomePathError(exceptionMessage: String)
+    extends BuildException(message =
+      s"""The java home path argument in the using directives at could not be found!
+         |$exceptionMessage""".stripMargin) {}
+//TODO "at where?"
```
Comment (romanowski) [inline modules/directives/src/main/scala/scala/build/errors/WrongJavaHomePathError.scala]: TODO?

File: modules/directives/src/main/scala/scala/build/preprocessing/directives/DirectiveHandler.scala [hunk 7]
```diff
@@ -15,10 +27,136 @@ trait DirectiveHandler[T] {
...
-    cwd: ScopePath,
+    scopedDirective: ScopedDirective,
     logger: Logger
   ): Either[BuildException, ProcessedDirective[T]]
 
+  /** It checks if the values assigned to the key of the scopedDirective have the expected type or
+    * number.
+    *
+    * Note: the correct functioning of this method for some of the handlers might require overriding
+    * the implementations for [[getSupportedTypes]], [[getValueNumberBounds]], and
```
Comment (romanowski) [inline modules/directives/src/main/scala/scala/build/preprocessing/directives/DirectiveHandler.scala:38]: This is really superb pice of scaladoc - provides just the information needed - I really like it.

File: modules/directives/src/main/scala/scala/build/preprocessing/directives/DirectiveHandler.scala [hunk 8]
```diff
@@ -15,10 +27,136 @@ trait DirectiveHandler[T] {
...
+    */
+  final protected def receiveTheRightNumberOfValues(
+    scopedDirective: ScopedDirective
+  ): Either[UsingDirectiveExpectationError, ScopedDirective] = {
+    val values: Seq[Value[_]] = scopedDirective.directive.values.collect {
+      case n: NumericValue => n
+      case b: BooleanValue =>
+        b
+      case s: StringValue => s
+    } // TODO or perhaps `.filterNot(_.isInstanceOf[EmptyValue])` ??
```
Comment (romanowski) [inline modules/directives/src/main/scala/scala/build/preprocessing/directives/DirectiveHandler.scala]: I think `filterNot` is better apprach, especially combined with a function `isEmptyValue(v: Value) = v isInstanceOf[EmptyValue]`

File: modules/directives/src/main/scala/scala/build/preprocessing/directives/DirectiveHandler.scala [hunk 9]
```diff
@@ -15,10 +27,136 @@ trait DirectiveHandler[T] {
...
+  /** checks if the passed in `scopedDirective` has the expected number of values according to the
+    * implementation of [[getValueNumberBounds]] for the handler on which this is called
+    *
+    * @return
+    *   Either a [[UsingDirectiveExpectationError]] or the same passed in scopedDirective
+    */
+  final protected def receiveTheRightNumberOfValues(
+    scopedDirective: ScopedDirective
+  ): Either[UsingDirectiveExpectationError, ScopedDirective] = {
+    val values: Seq[Value[_]] = scopedDirective.directive.values.collect {
```
Comment (romanowski) [inline modules/directives/src/main/scala/scala/build/preprocessing/directives/DirectiveHandler.scala]: NIT: I would call this val a `nonEmptyValues`

File: modules/directives/src/main/scala/scala/build/preprocessing/directives/DirectiveHandler.scala [hunk 10]
```diff
@@ -15,10 +27,136 @@ trait DirectiveHandler[T] {
...
+
+  /** It checks the values ascribed to the key inside the passed in `scopedDirective`, in order to
+    * see if they are of the types listed to be expected by the implementation of
+    * [[getSupportedTypes]] inside the specific handler.
+    *
+    * @return
+    *   Either a [[UsingDirectiveExpectationError]] or the using directive values of the
+    *   `scopedDirective` grouped in `string`, `boolean`, or `numeric` sequences.
+    */
+  final protected def siftSupportedValueTypesWithNoResidue(
```
Comment (romanowski) [inline modules/directives/src/main/scala/scala/build/preprocessing/directives/DirectiveHandler.scala]: `siftSupportedValueTypesWithNoResidue ` describes what this methods does however it is a bit hard to understand at first glance. Maybe something long the line of `checkAndGroupValuesByType`?

File: modules/directives/src/main/scala/scala/build/preprocessing/directives/UsingCompilerPluginDirectiveHandler.scala [hunk 11]
```diff
@@ -24,34 +22,38 @@ case object UsingCompilerPluginDirectiveHandler extends UsingDirectiveHandler {
       .left.map(err => new DependencyFormatError(depStr, err))
 
   def keys = Seq("plugin", "plugins")
+
+  override def getValueNumberBounds(key: String): UsingDirectiveValueNumberBounds = key match {
+    case "plugin"  => UsingDirectiveValueNumberBounds(1, Int.MaxValue)
```
Comment (romanowski) [inline modules/directives/src/main/scala/scala/build/preprocessing/directives/UsingCompilerPluginDirectiveHandler.scala]: Can't we just return `UsingDirectiveValueNumberBounds(1, Int.MaxValue)` ?

File: modules/directives/src/main/scala/scala/build/preprocessing/directives/UsingPublishDirectiveHandler.scala [hunk 12]
```diff
@@ -50,54 +48,62 @@ case object UsingPublishDirectiveHandler extends UsingDirectiveHandler {
...
-    path: Either[String, os.Path],
-    cwd: ScopePath,
+    scopedDirective: ScopedDirective,
     logger: Logger
-  ): Either[BuildException, ProcessedUsingDirective] = either {
-    def singleValue   = DirectiveUtil.singleStringValue(directive, path, cwd)
-    def severalValues = DirectiveUtil.stringValues(directive.values, path, cwd)
+  ): Either[BuildException, ProcessedUsingDirective] =
+    checkIfValuesAreExpected(scopedDirective).flatMap { groupedScopedValuesContainer =>
+      // This head is fishy!
```
Comment (romanowski) [inline modules/directives/src/main/scala/scala/build/preprocessing/directives/UsingPublishDirectiveHandler.scala]: Sort of since we specify that we will have at least single element

File: modules/options/src/main/scala/scala/build/Positioned.scala [hunk 13]
```diff
@@ -20,6 +20,8 @@ final case class Positioned[+T](
       pos0.value
     )
   }
+
+  // override def toString = s"$value at positions ${positions.mkString(", ")}"
```
Comment (romanowski) [inline modules/options/src/main/scala/scala/build/Positioned.scala]:
```suggestion
```

**Review by romanowski — CHANGES_REQUESTED** [review]
Some clean up, renames are required but beside the code looks ok.

File: modules/directives/src/main/scala/scala/build/directives/ScopedValue.scala (hunk 2 above)
Comment (ghost) [reply modules/directives/src/main/scala/scala/build/directives/ScopedValue.scala]: I need to take a look at this… It might actually be commented only for debugging...

File: modules/directives/src/main/scala/scala/build/errors/WrongJavaHomePathError.scala (hunk 6 above)
Comment (ghost) [reply modules/directives/src/main/scala/scala/build/errors/WrongJavaHomePathError.scala]: yes… it has to include the address. There should be a dedicated argument for that.

File: modules/options/src/main/scala/scala/build/Positioned.scala (hunk 13 above)
Comment (ghost) [reply modules/options/src/main/scala/scala/build/Positioned.scala]: I need to make sure, that the commenting is not for debugging purposes.

File: modules/directives/src/main/scala/scala/build/preprocessing/directives/UsingPublishDirectiveHandler.scala (hunk 12 above)
Comment (ghost) [reply modules/directives/src/main/scala/scala/build/preprocessing/directives/UsingPublishDirectiveHandler.scala]: would definitely double check that...

File: modules/directives/src/main/scala/scala/build/directives/UsingDirectiveValueNumberBounds.scala (hunk 3 above)
Comment (ghost) [reply modules/directives/src/main/scala/scala/build/directives/UsingDirectiveValueNumberBounds.scala:3]: This is only instantiated once in the `recieveTheRightNumberOfValues`
Breaking it down to multiple values,requires changing the logic therefrom its current clean form, to check for the concrete values of the lower and upper bounds...

File: modules/directives/src/main/scala/scala/build/preprocessing/directives/UsingPublishDirectiveHandler.scala (hunk 12 above)
Comment (ghost) [reply modules/directives/src/main/scala/scala/build/preprocessing/directives/UsingPublishDirectiveHandler.scala]: Yes, because checking the values ensures that.

**Review by romanowski — APPROVED** [review]
