### PR TITLE
Remove irrelevant options from `version` help message

### LINKED ISSUE #1666: Output of `scala version --help` could be more helpful
**Version(s)**

0.1.18 installed via `cs install scala-experimental`

**Describe the bug**

Currently, the output of `scala version --help` is the following:

~~~ text
$ scala version --help
Usage: /home/julien/.local/share/coursier/bin/.scala.aux version [options]
Print version

Help options:
  --usage                                        Print usage and exit
  -h, -help, --help                              Print help message and exit
  -help-full, -full-help, --help-full, --full-help  Print help message, including hidden options, and exit

Logging options:
  -v, --verbose  Increase verbosity (can be specified multiple times)
  -q, --quiet    Decrease verbosity
  --progress     Use progress bars

Other options:
  -i, --interactive         Interactive mode
  --actions                 Enable actionable diagnostics
  --cli, --cli-version      Show only plain version
  --scala, --scala-version  Show only plain scala version
~~~

I think the only really helpful options of the `scala version` command are `--cli` and `--scala`, but they are shown at the very bottom, after options like `--interactive` and `--actions` which seem irrelevant.

**Expected behaviour**

~~~ text
$ scala version --help
Usage: scala version [options]
Print the version of the scala runner and the default version of Scala (unless specified in the project).

The version of the scala runner is the version of the command-line tool that runs Scala programs, which
is distinct from the Scala version of a program. We recommend you specify the version of Scala of a
program in the program itself (via a configuration directive). Otherwise, the runner falls back to the default
Scala version defined by the runner.

Main options:
  --cli, --cli-version      Show only the version of the command-line runner
  --scala, --scala-version  Show only the default Scala version used by the runner

Help options:
  --usage                                        Print usage and exit
  -h, -help, --help                              Print help message and exit
~~~

I suggest dropping the options that have no effects at all (such as `--help-full`, `--verbose`, `--quiet`, `--progress`, `--actions`, `--interactive`, if I understand correctly but I could be wrong), clarifying the documentation, and moving the options `--cli` and `--scala` as “Main options”.

### PR DESCRIPTION
**Pull request by lwronski**
It change the output of `version` help message  to:
```
Usage: scala-cli version [options]
Print the version of the scala runner and the default version of Scala (unless specified in the project).

The version of the scala runner is the version of the command-line tool that runs Scala programs, which
is distinct from the Scala version of a program. We recommend you specify the version of Scala of a
program in the program itself (via a configuration directive). Otherwise, the runner falls back to the default
Scala version defined by the runner.

Version options:
  --cli, --cli-version      Show only plain version
  --scala, --scala-version  Show only plain scala version

Help options:
  --usage            Print usage and exit
  -h, -help, --help  Print help message and exit

```

I added @julienrf as co-authored commit who created the help message content. Help message was copied from https://github.com/VirtusLab/scala-cli/issues/1666#issue-1484074598.

Fixes #1666.

### CODE REVIEW

File: modules/cli/src/test/scala/cli/tests/HelpCheck.scala [hunk 1]
```diff
@@ -11,4 +14,14 @@ class HelpCheck extends munit.FunSuite {
     val lines = helpMessage.split("\r\n|\r|\n").length
     assert(lines <= 80)
   }
+
+  test("version help message should contains only relevant options") { // regression test - https://github.com/VirtusLab/scala-cli/issues/1666
```
Comment (Gedochao) [inline modules/cli/src/test/scala/cli/tests/HelpCheck.scala]: NIT
```suggestion
  test("version help message should only contain relevant options") { // regression test - https://github.com/VirtusLab/scala-cli/issues/1666
```

**Review by Gedochao — APPROVED** [review]
