### PR TITLE
Ensure test source directives with test scope equivalents are migrated by `fix` to `project.scala`

### LINKED ISSUE #3409: `fix` sub-command merges directives accepting lists of values into super-long lines
**Version(s)**
d8b33133f732eaf6ada88a3dbe0c3166d555d8e5 / 1.5.4-94-gd8b33133f-SNAPSHOT

**Describe the bug**
When running the `fix` sub-command's built-in rules, directives from multiple files are migrated into the `project.scala` configuration file.
When a directive key accepting multiple values (i.e. `//> using dep`) is repeated across the project, Scala CLI will merge it into a single directive.
The resulting directive can then be unreasonably long.

**To Reproduce**
given
```scala
// file1.scala
//> using dep com.lihaoyi::os-lib:0.9.1
```

```scala
// file2.scala
//> using dep com.lihaoyi::pprint:0.8.0
```

```scala
//file3.scala
//> using  dep org.scala-lang::scala3-compiler:3.6.2
```

the resulting `project.scala` looks like this:
```scala
// Main
//> using dependency "com.lihaoyi::os-lib:0.9.1"  "com.lihaoyi::pprint:0.8.0" "org.scala-lang::scala3-compiler:3.6.2"
```

**Expected behaviour**
Directives in `project.scala` should hold to a reasonable line length after migrating with `fix`.

### LINKED ISSUE #3410: `test.dep` directives aren't migrated from test scope files by `fix`
**Version(s)**
https://github.com/VirtusLab/scala-cli/commit/d8b33133f732eaf6ada88a3dbe0c3166d555d8e5 / 1.5.4-94-gd8b33133f-SNAPSHOT

**Describe the bug**
When migrating directives with `fix` sub-command built-in rules, `//> using dep` directives from test scope files get migrated to `//> using test.dependency` directives in `project.scala.
However, inconsistently with that, `//> using test.dependency` directives from test scope files don't get migrated at all.

**To Reproduce**
given
```scala
//> main.scala
//> using test.dependency "com.lihaoyi::os-lib:0.9.3"
```
and
```scala
//> smth.test.scala
//> using test.dependency org.scalatest::scalatest::3.2.9
//> using dep com.lihaoyi::pprint:0.9.0
```
when running
```bash
scala-cli fix . --power
# Some utilized features are marked as experimental:
#  - `fix` sub-command
#  - `--enable-scalafix=false` option
# Please bear in mind that non-ideal user experience should be expected.
# If you encounter any bugs or have feedback to share, make sure to reach out to the maintenance team at https://github.com/VirtusLab/scala-cli
# Running built-in rules...
# Writing project.scala
# Removing directives from smth.test.scala
#   Keeping:
#     //> using test.dependency org.scalatest::scalatest::3.2.9
# Built-in rules completed.
```
the resulting project configuration looks like this:
```scala
// project.scala
// Test
//> using test.dependency "com.lihaoyi::os-lib:0.9.3" "com.lihaoyi::pprint:0.9.0"
```
with one of the directives in `smth.test.scala` being kept back:
```scala
//> using test.dependency org.scalatest::scalatest::3.2.9
```

**Expected behaviour**
All `//> using test.dependency` directives should get migrated in this case.

### PR DESCRIPTION
**Pull request by Gedochao**
Fixes #3410 
Fixes #3409 (actually already works as expected, with the line length limit equal to 100 characters atm; a test is added in this PR)
Requires:
- #3422 

So the tricky part is that, when migrating directives from test sources to the `project.scala` configuration file, we can only migrate the ones which have test scope equivalents.
`//> using dep` has an equivalent in `//> using test.dep`, but `//> using scala` has none.
So the directives with no equivalents have to stay where they are, otherwise behaviour will change.

### CODE REVIEW

File: modules/integration/src/test/scala/scala/cli/integration/FixBuiltInRulesTestDefinitions.scala [hunk 1]
```diff
@@ -447,4 +447,81 @@ trait FixBuiltInRulesTestDefinitions { _: FixTestDefinitions =>
...
+          expect(!os.exists(root / projectFileName))
+          expect(os.read(root / inputFileName) == code)
+          val runResult = os.proc(TestUtil.cli, "run", ".", extraOptions)
+            .call(cwd = root, stderr = os.Pipe)
+          expect(runResult.out.trim() == root.toString)
+        }
+      }
+  }
+
+  if (!Properties.isWin)
```
Comment (Gedochao) [inline modules/integration/src/test/scala/scala/cli/integration/FixBuiltInRulesTestDefinitions.scala:485]: As usual, the CI has problems on Windows...

Comment (Gedochao) [reply modules/integration/src/test/scala/scala/cli/integration/FixBuiltInRulesTestDefinitions.scala:485]: - https://github.com/VirtusLab/scala-cli/issues/3428

File: modules/integration/src/test/scala/scala/cli/integration/FixBuiltInRulesTestDefinitions.scala [hunk 2]
```diff
@@ -447,4 +447,81 @@ trait FixBuiltInRulesTestDefinitions { _: FixTestDefinitions =>
...
+                           |  test("hello") {
+                           |    pprint.pprintln(os.pwd)
+                           |    assert(Main.hello == "Hello, world!")
+                           |  }
+                           |}
+                           |""".stripMargin
+      ).fromRoot { root =>
+        os.proc(TestUtil.cli, "--power", "fix", ".", extraOptions).call(cwd = root)
+        val projectFileContents = os.read(root / projectFileName)
+        expect(projectFileContents.contains(munitTestDepDirective))
```
Comment (tgodzik) [inline modules/integration/src/test/scala/scala/cli/integration/FixBuiltInRulesTestDefinitions.scala]: Could we compare the whole expected file?

**Review by tgodzik — APPROVED** [review]
One nitpick otherwise LGTM

File: modules/integration/src/test/scala/scala/cli/integration/FixBuiltInRulesTestDefinitions.scala (hunk 2 above)
Comment (Gedochao) [reply modules/integration/src/test/scala/scala/cli/integration/FixBuiltInRulesTestDefinitions.scala]: done
