### PR TITLE
fix for #3481

### LINKED ISSUE #3481: scala-cli -e 'println("hello")' > /dev/null    throws java.io.IOException
**Version(s)**
```bash
# scala-cli --version
Scala CLI version: 1.6.1
Scala version (default): 3.6.3
```

**Describe the bug**
Redirecting stdout to /dev/null throws an Exception.
```scala
java.io.IOException: Error enabling ANSI output: GetConsoleMode error 6
  coursier.jniutils.WindowsAnsiTerminal.enableAnsiOutput(WindowsAnsiTerminal.java:25)
  scala.cli.ScalaCli$.main0(ScalaCli.scala:317)
  scala.cli.ScalaCli$.main(ScalaCli.scala:124)
  scala.cli.ScalaCli.main(ScalaCli.scala)
```

**To Reproduce**
hello.sc:
```scala
#!/usr/bin/env -S scala-cli shebang
printf("%s\n", "hello")
```
```bash
./hello.sc
hello
scala-cli -e 'println("hello")'  > /dev/null
Error: java.io.IOException: Error enabling ANSI output: GetConsoleMode error 6
For more details, please see 'C:\opt\ue\.scala-build\stacktraces\1738864818-3992728134502856876.log'
```

Should not throw an exception.

### PR DESCRIPTION
**Pull request by philwalk**
This addresses issue #3481.

In Windows, when STDOUT is redirected to `/dev/null` an exception is thrown:
```sh
scala.bat -e "printf("""hello""")" > NUL
```
```scala
java.io.IOException: Error enabling ANSI output: GetConsoleMode error 6
  coursier.jniutils.WindowsAnsiTerminal.enableAnsiOutput(WindowsAnsiTerminal.java:25)
  scala.cli.ScalaCli$.main0(ScalaCli.scala:317)
  scala.cli.ScalaCli$.main(ScalaCli.scala:124)
  scala.cli.ScalaCli.main(ScalaCli.scala)
```

The fix, only in Windows, is to selectively ignore `java.io.IOException` if `getMessage` contains `'GetConsoleMode error 6`.

Error 6 means "invalid handle", and is appropriate since `stdout` redirected to NUL is not a console handle.
Since everything sent to `stdout` is discarded, it shouldn't matter that `Ansi` mode is not enabled.

The documentation for [GetConsoleScreenBufferInfo](https://learn.microsoft.com/en-us/windows/console/getconsolescreenbufferinfo#:~:text=This%20API%20does,on%20ReadConsoleInput.) describes limitations.

Just noticed that the 2nd `isWin` in the exception handling is redundant.

### CODE REVIEW

**Comment by philwalk** [comment]
Here are manual test sessions demonstrating the fix:
```scala
philwalk@d5 MINGW64 ~
# scala-cli -e 'System.err.println("hello")'
Compiling project (Scala 3.7.0, JVM (17))
Compiled project (Scala 3.7.0, JVM (17))
hello

philwalk@d5 MINGW64 ~
# scala-cli -e 'System.err.println("hello")' > /dev/null
Compiling project (Scala 3.7.0, JVM (17))
Compiled project (Scala 3.7.0, JVM (17))
hello
```
in a `CMD.EXE` session:
```CMD
C:\opt\ue>scala-cli.exe -e "System.err.println("""hello""")"
Compiling project (Scala 3.7.0, JVM (11))
Compiled project (Scala 3.7.0, JVM (11))
hello

C:\opt\ue>scala-cli.exe -e "System.err.println("""hello""")" > NUL
Compiling project (Scala 3.7.0, JVM (11))
Compiled project (Scala 3.7.0, JVM (11))
hello
```

File: modules/cli/src/main/scala/scala/cli/ScalaCli.scala [hunk 1]
```diff
@@ -314,7 +314,13 @@ object ScalaCli {
 
     if (Properties.isWin && System.console() != null && coursier.paths.Util.useJni())
       // Enable ANSI output in Windows terminal
-      coursier.jniutils.WindowsAnsiTerminal.enableAnsiOutput()
+      try
+        coursier.jniutils.WindowsAnsiTerminal.enableAnsiOutput()
+      catch {
+        // ignore error resulting from redirect STDOUT to /dev/null
+        case e: java.io.IOException
+            if Properties.isWin && e.getMessage.contains("GetConsoleMode error 6") =>
```
Comment (Gedochao) [inline modules/cli/src/main/scala/scala/cli/ScalaCli.scala]:
```suggestion
            if e.getMessage.contains("GetConsoleMode error 6") =>
```

**Comment by Gedochao** [comment]
@philwalk do you think we could have an integration test for this (behind `if Properties.isWin`)? we do run tests on Windows runners.

**Comment by philwalk** [comment]
> do you think we could have an integration test for this (behind `if Properties.isWin`)?

How about if I copy a similar existing test and redirect `stdout` to `NUL`?
 
This one seems like a good candidate: ["correctly run a scala snippet"](https://github.com/VirtusLab/scala-cli/blob/40e77b1a698bd64ec61b917713d00051a59dcb6c/modules/integration/src/test/scala/scala/cli/integration/RunSnippetTestDefinitions.scala#L23).   Here's the modified copy:
```scala
  test("confirm that redirecting stdout to NUL doesn't throw an exception") {
    if (scala.util.Properties.isWin) {
      val nulPath = os.Path("NUL", os.pwd)
      emptyInputs.fromRoot { root =>
        val msg       = "Hello world"
        val quotation = TestUtil.argQuotationMark
        val res =
          os.proc(
            TestUtil.cli,
            "run",
            "--scala-snippet",
            s"object Hello extends App { System.err.println($quotation$msg$quotation) }",
            extraOptions
          )
            .call(cwd = root, stdout = nulPath)
        expect(res.out.trim() == msg)
      }
    }
  }
```
I haven't yet verified that the `nullPath` object does what we want, but you get the idea.

**Comment by philwalk** [comment]
I can reproduce the problem from a Windows batch file, but it only fails when I run it manually.
Here's the one-line `batch` file:
```batch
::# contents of crash.bat:
scala-cli.exe  -e System.err.println("""Hello World""") --server=false > NUL

C:\opt\ue>crash.bat
Error: java.io.IOException: Error enabling ANSI output: GetConsoleMode error 6
For more details, please see 'C:\opt\ue\.scala-build\stacktraces\1747424901-506732676395670742.log'
```
If I spawn the same batch file from within a scala program, the failure is somehow avoided.
There seems to be some magic that occurs within `sys.process` and within `os.proc`.

scala script `crashsysprocess.sc`:
```scala

val msg = "Hello World"
import scala.sys.process.*
val stdout = new StringBuilder
val stderr = new StringBuilder
val status = Seq("cmd.exe", "/c.\\\\crash.bat") ! ProcessLogger(stdout append _, stderr append _)
val out = stdout.toString.trim
val err = stderr.toString.trim
printf("status[%s], stdout[%s], stderr[%s]\n", status, out, err)
assert(msg == err)

# ./crashsysprocess.sc
status[0], stdout[], stderr[Hello World]
```

scala script `crashosproc.sc`:
```scala
#!/usr/bin/env -S scala-cli shebang
//> using dep com.lihaoyi::os-lib:0.11.4
// crash.bat redirects stdout to NUL
// call `crash.bat` to demonstrate #3481
val res = os.proc(".\\crash.bat").call()
printf("res.out[%s]\n", res.out.trim())
printf("res.err[%s]\n", res.err.trim())

# ./crashosproc.sc
Compiling project (Scala 3.7.0, JVM (17))
Compiled project (Scala 3.7.0, JVM (17))
Hello World
res.out[]
res.err[]
```

All the various other things I have tried fail to reproduce this bug.
I have concluded that it's not possible with `os.proc`  or `scala.sys.process` to redirect to Windows `NUL`

**Comment by philwalk** [comment]
I'm tempted to click the "Update branch" button, what's the recommended practice?
The message currently says:
image

**Comment by Gedochao** [comment]
> I'm tempted to click the "Update branch" button, what's the recommended practice? 

Updating the branch will merge `main` to your branch / rebase on top of it. While it is recommended, do keep in mind it will also restart the CI.

**Comment by Gedochao** [comment]
> All the various other things I have tried fail to reproduce this bug.
I have concluded that it's not possible with os.proc or scala.sys.process to redirect to Windows NUL

Yeah, I thought that might be the case. I think we can live without a test then.

**Review by Gedochao — APPROVED** [review]
