### PR TITLE
tests: Add tests for issue with rereporting errors

### LINKED ISSUE #2226: Scala CLI prints errors from the previous compilation
**Version(s)**
1.0.1

**Describe the bug**
Scala CLI prints errors from the previous compilation

**To Reproduce**
```
$ cat Hello.scala
//> using scala 3.3.0

object Main extends App {
    val msg: String = "1"
}
$ scala-cli compile Hello.scala
Compiling project (Scala 3.3.0, JVM)
Compiled project (Scala 3.3.0, JVM)
$ cat Hello.scala
//> using scala 3.3.0

object Main extends App {
    val msg: String = 1
}
scala-cli compile Hello.scala
Compiling project (Scala 3.3.0, JVM)
[error] ./Hello.scala:4:23
[error] Found:    (1 : Int)
[error] Required: String
[error]     val msg: String = 1
[error]                       ^
Error compiling project (Scala 3.3.0, JVM)
Compilation failed
$ cat Hello.scala
//> using scala 3.3.0

object Main extends App {
    val msg: String = "1"
}
$ scala-cli compile Hello.scala
[error] ./Hello.scala:4:23
[error] Found:    (1 : Int)
[error] Required: String
[error]     val msg: String = "1"
[error]                       ^
```

It should not print the error at the end because the code is compiling fine.

### PR DESCRIPTION
**Pull request by tgodzik**
Fixes https://github.com/VirtusLab/scala-cli/issues/2226

### CODE REVIEW

**Review by Gedochao — APPROVED** [review]
LGTM
it just needs a rebase, it seems

File: modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala [hunk 1]
```diff
@@ -737,4 +737,81 @@ abstract class CompileTestDefinitions
...
+    val filename = "Main.scala"
+    val inputs = TestInputs(
+      os.rel / filename ->
+        """|object Main extends App {
+           |  val msg: String = "1"
+           |}
+           |""".stripMargin
+    )
+    inputs.fromRoot { root =>
+      val result = os.proc(TestUtil.cli, "compile", ".").call(
```
Comment (Gedochao) [inline modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala]:
```suggestion
      val result = os.proc(TestUtil.cli, "compile", ".", extraOptions).call(
```

File: modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala [hunk 2]
```diff
@@ -737,4 +737,81 @@ abstract class CompileTestDefinitions
...
+
+      os.write.over(
+        root / filename,
+        """|object Main extends App {
+           |    val msg: String = 1
+           |}
+           |""".stripMargin
+      )
+
+      val result2 = os.proc(TestUtil.cli, "compile", ".").call(
```
Comment (Gedochao) [inline modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala]:
```suggestion
      val result2 = os.proc(TestUtil.cli, "compile", ".", extraOptions).call(
```

File: modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala [hunk 3]
```diff
@@ -737,4 +737,81 @@ abstract class CompileTestDefinitions
...
+
+      os.write.over(
+        root / filename,
+        """|object Main extends App {
+           |    val msg: String = "1"
+           |}
+           |""".stripMargin
+      )
+
+      val result3 = os.proc(TestUtil.cli, "compile", ".").call(
```
Comment (Gedochao) [inline modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala]:
```suggestion
      val result3 = os.proc(TestUtil.cli, "compile", ".", extraOptions).call(
```
