### PR TITLE
Bloop workspace dir

### LINKED ISSUE #443: Current directory when running via BSP is set to `.scala`
To reproduce:

Run below snippet from within metals and from cli.

```scala
// using lib com.lihaoyi::os-lib:0.7.8

@main
def main =
  println(os.pwd) 
end main
```

### PR DESCRIPTION
**Pull request by lwronski**
Set workspace directory to current dir where scala-cli is running in BSP.

### CODE REVIEW

**Review by alexarchambault — APPROVED** [review]
If the CI is green, LGTM!

**Review by romanowski — APPROVED** [review]

File: modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala [hunk 1]
```diff
@@ -1234,4 +1234,21 @@ abstract class RunTestDefinitions(val scalaVersionOpt: Option[String])
...
+        os.rel / "Hello.scala" ->
+          """|// using lib com.lihaoyi::os-lib:0.7.8
+             |
+             |object Hello extends App {
+             |  println(os.pwd) 
+             |}""".stripMargin
+      )
+    )
+    inputs.fromRoot { root =>
+      val p = os.proc(TestUtil.cli, "Hello.scala").call(cwd = root)
```
Comment (tpasternak) [inline modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala:1250]: I'm not sure if this test really tests the code that has been change. When you run `scala-cli run ... ` it takes the cwd from `Inputs`, which just takes os.Pwd https://github.com/VirtusLab/scala-cli/blob/75b04cc08d265423cd608f3cebc75d18ba181dd4/modules/cli/src/main/scala/scala/cli/commands/SharedOptions.scala#L218

So it passes even without the change. In order to test it, you need to run `scala-cli bsp`

**Comment by tpasternak** [comment]
I would also test if clean works correctly after this change
