### PR TITLE
Don't migrate directives with `fix` for single-file projects

### LINKED ISSUE #3411: don't let `fix` migrate directives in single-file projects
**Version(s)**
https://github.com/VirtusLab/scala-cli/commit/d8b33133f732eaf6ada88a3dbe0c3166d555d8e5 / 1.5.4-94-gd8b33133f-SNAPSHOT

**Describe the bug**
When running the `fix` sub-command built-in rules, directives are migrated to the `project.scala` configuration file even with single-file projects (including standalone `.sc` scripts.

**To Reproduce**
```scala
// script.sc
//> using scala "3"
//> using jvm "17"
println("Hello!")
```
run `fix`:
```bash
scala-cli fix . --power
# The `fix` sub-command is experimental
# Please bear in mind that non-ideal user experience should be expected.
# If you encounter any bugs or have feedback to share, make sure to reach out to the maintenance team at https://github.com/VirtusLab/scala-cli
# Running built-in rules...
# Writing project.scala
# Removing directives from smth.sc
# Built-in rules completed.
# Running scalafix rules...
# Compiling project (Scala 3.6.2, JVM (17))
# Compiled project (Scala 3.6.2, JVM (17))
# No rules requested to run
```
`project.scala` gets created (unnecessarily):
```scala
// Main
//> using scala "3"
//> using jvm "17"
```

**Expected behaviour**
Just don't create `project.scala` for single-file projects.

### PR DESCRIPTION
**Pull request by Gedochao**
Fixes #3411

### CODE REVIEW

File: modules/integration/src/test/scala/scala/cli/integration/FixBuiltInRulesTestDefinitions.scala [hunk 1]
```diff
@@ -447,4 +447,38 @@ trait FixBuiltInRulesTestDefinitions { _: FixTestDefinitions =>
...
+        "raw.scala" -> s"""$directive
+                          |object Main extends App {
+                          |  println(os.pwd)
+                          |}
+                          |""".stripMargin,
+        "script.sc" -> s"""$directive
+                          |println(os.pwd)
+                          |""".stripMargin
+      )
+      if !Properties.isWin // TODO: make this run on Windows CI
```
Comment (Gedochao) [inline modules/integration/src/test/scala/scala/cli/integration/FixBuiltInRulesTestDefinitions.scala:464]: This fails similar to some of the previous PRs related to `fix`, and I'm not sure why.
Only Windows, though.
Has to be investigated separately.

Comment (Gedochao) [reply modules/integration/src/test/scala/scala/cli/integration/FixBuiltInRulesTestDefinitions.scala:464]: - https://github.com/VirtusLab/scala-cli/issues/3428

**Review by tgodzik — APPROVED** [review]
