### PR TITLE
Tweak the `fmt` command

### LINKED ISSUE #1121: `fmt` command does not respect the `project.excludePaths` setting
**Version(s)**

0.1.8

**Describe the bug**

the `project.excludePaths` setting in `.scalafmt.conf` is being ignored by Scala CLI's `fmt` command.

**To Reproduce**

```bash
▶ tree -a
.
├── .scalafmt.conf
├── ScalaMainClass1.scala
├── ScalaMainClass2.scala
├── scripts
│   └── ScalaScript.sc
└── src
    └── test
        └── scala
            └── ShouldNotFormat.scala
▶ cat .scalafmt.conf 
version = 3.5.2
runner.dialect = scala3
project {
  includePaths = [
    "glob:**.scala",
    "regex:.*\\.sc"
  ]
  excludePaths = [
    "glob:**/src/test/scala/**.scala"
  ]
}

▶ scalafmt . --test
All files are formatted with scalafmt :)

▶ scala-cli fmt . --check
--- a/Users/pchabelski/IdeaProjects/scala-cli-tests/scalafmt-test/src/test/scala/ShouldNotFormat.scala
+++ b/Users/pchabelski/IdeaProjects/scala-cli-tests/scalafmt-test/src/test/scala/ShouldNotFormat.scala
@@ -1,3 +1,3 @@
 class ShouldNotFormat {
-                    println()
+  println()
 }
error: --test failed
```

**Expected behaviour**
Scala CLI should exactly mimic the behaviour of `scalafmt` for this usecase

**Known workaround**
Passing the `--respect-project-filters` as a `scalafmt` arg explicitly solves it.
```bash
▶ scala-cli fmt . --check -F --respect-project-filters
```

### PR DESCRIPTION
**Pull request by Gedochao**
The aim of this PR (in the context of the `fmt` command)
- add a native alias for `scalafmt`'s `--respect-project-filters` and turn it on by default in Scala CLI
- add a native alias for `scalafmt`'s `--help` => `--scalafmt-help`
- refactor a bit
- add some tests
- improve the docs

### CODE REVIEW

File: modules/integration/src/test/scala/scala/cli/integration/FmtTests.scala [hunk 1]
```diff
@@ -57,4 +72,28 @@ class FmtTests extends munit.FunSuite {
     }
   }
 
+  test("filter correctly with --check") {
+    simpleInputsWithFilter.fromRoot { root =>
+      val out      = os.proc(TestUtil.cli, "fmt", ".", "--check").call(cwd = root).out.text.trim
```
Comment (lwronski) [inline modules/integration/src/test/scala/scala/cli/integration/FmtTests.scala:77]: Did you check, if scala-cli overrides defined `runner.dialect = scala213` in `.scalafmt.conf` by cli options?

Scala CLi resolve `runner.dialect` base on scala params [here](https://github.com/VirtusLab/scala-cli/blob/b754d2afdda114e97febfb0090773cc582bafd19/modules/cli/src/main/scala/scala/cli/commands/Fmt.scala#L160) and then pass to scalafmt args

Comment (Gedochao) [reply modules/integration/src/test/scala/scala/cli/integration/FmtTests.scala:77]:
```
▶ cat .scalafmt.conf
version = 3.5.2
runner.dialect = scala3
project {
  includePaths = [
    "glob:**.scala",
    "regex:.*\\.sc"
  ]
  excludePaths = [
    "glob:**/src/test/scala/**.scala"
  ]
}
 
▶ scala-cli-prototype fmt . --dialect scala213
/Users/pchabelski/IdeaProjects/scala-cli-tests/scalafmt-dialects/s3.scala:4: error: [dialect scala3] identifier expected but class found
enum class Weekday {
     ^
 ```
 seems to work correctly. whatever is defined in `.scalafmt.conf` has priority, as it should.
 if necessary, I can add an integration test for this, as I don't see one. Thoughts?

**Review by alexarchambault — APPROVED** [review]
