### PR TITLE
`fix` built-in rules: don't wrap directive values in double quotes if not necessary

### LINKED ISSUE #3052: --fix Command Boolean Handling
**Version(s)**
Scala CLI version: 1.4.1
Scala version (default): 3.4.2

**Describe the bug**
When executing `scala-cli --power fix .`, boolean values in directives are written as a string, example, `true` is `"true"`

**To Reproduce**
Add, `//> using jsEmitSourceMaps true` to your `project.scala` and execute the command above.

**Expected behavior**
Boolean values should not be wrapped in a string

### PR DESCRIPTION
**Pull request by Gedochao**
Fixes #3052

### CODE REVIEW

**Review by tgodzik — CHANGES_REQUESTED** [review]
Looks like some tests are still failing

**Comment by Gedochao** [comment]
> Looks like some tests are still failing

@tgodzik the failures seem unrelated to this PR, and seem to be caused by Scala Native not supporting Scala 2.13.16 at the time the CI was being run.
Restarted the CI.

**Comment by Gedochao** [comment]
Rebased & added a retry on the CI for a test using Scala Native (it seems there may have been an intermittent timeout there for one test)

**Comment by Gedochao** [comment]
Adjusted the `using directives with boolean values are handled correctly` test to check a different boolean directive (`//> using python`)

File: modules/integration/src/test/scala/scala/cli/integration/FixBuiltInRulesTestDefinitions.scala [hunk 1]
```diff
@@ -425,4 +419,32 @@ trait FixBuiltInRulesTestDefinitions { _: FixTestDefinitions =>
       )
     }
   }
+
+  if (!Properties.isWin) // TODO: fix this test for Windows CI
```
Comment (Gedochao) [inline modules/integration/src/test/scala/scala/cli/integration/FixBuiltInRulesTestDefinitions.scala:423]: @tgodzik no idea why this is failing on Windows CI, I'll investigate as a follow-up

**Review by tgodzik — APPROVED** [review]

File: modules/integration/src/test/scala/scala/cli/integration/FixBuiltInRulesTestDefinitions.scala (hunk 1 above)
Comment (Gedochao) [reply modules/integration/src/test/scala/scala/cli/integration/FixBuiltInRulesTestDefinitions.scala:423]: https://github.com/VirtusLab/scala-cli/issues/3428
