### PR TITLE
Separate Scala REPL classpath from user dependencies

### LINKED ISSUE #2582: REPL fails to start with `scalameta` as `dep`
**Version(s)**
```
scala-cli version
Scala CLI version: 1.0.6
Scala version (default): 3.3.1
```

**Describe the bug**
`scala` REPL throws or `SIGSEGV`s when using `scalameta` as `dep`

**To Reproduce**

With default JVM:
```
scala-cli --dep org.scalameta:scalameta_2.13:4.8.14
Welcome to Scala 3.3.1 (21.0.1, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
Exception in thread "main" com.sun.jna.LastErrorException: [14] Bad address
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:415)
	at com.sun.jna.Function.invoke(Function.java:361)
	at com.sun.jna.Library$Handler.invoke(Library.java:270)
	at jdk.proxy1/jdk.proxy1.$Proxy0.ioctl(Unknown Source)
	at org.jline.terminal.impl.jna.osx.OsXNativePty.getSize(OsXNativePty.java:82)
	at org.jline.terminal.impl.AbstractPosixTerminal.getSize(AbstractPosixTerminal.java:60)
	at org.jline.terminal.Terminal.getBufferSize(Terminal.java:217)
	at org.jline.reader.impl.LineReaderImpl.doDisplay(LineReaderImpl.java:755)
	at org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:308)
	at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:121)
	at dotty.tools.repl.JLineTerminal.readLine(JLineTerminal.scala:72)
	at dotty.tools.repl.ReplDriver.readLine$1(ReplDriver.scala:157)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:167)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:172)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:211)
	at dotty.tools.repl.ReplDriver.runBody$$anonfun$1(ReplDriver.scala:185)
	at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80)
	at dotty.tools.repl.ReplDriver.runBody(ReplDriver.scala:185)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:172)
	at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:134)
	at dotty.tools.repl.Main$.main(Main.scala:7)
	at dotty.tools.repl.Main.main(Main.scala)
```

With JVM 17:
```
scala-cli --jvm 17 --dep org.scalameta:scalameta_2.13:4.8.14

Welcome to Scala 3.3.1 (17.0.9, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000102d7ea20, pid=79350, tid=10243
#
# JRE version: OpenJDK Runtime Environment Zulu17.46+19-CA (17.0.9+8) (build 17.0.9+8-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu17.46+19-CA (17.0.9+8-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# C  [jna7748573358245533514.tmp+0xea20]  ffi_call+0x530
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/pprazak/repos/besom/hs_err_pid79350.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Abort trap: 6
```

logs fragment:
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.jna.Native.invokeVoid(Lcom/sun/jna/Function;JI[Ljava/lang/Object;)V+0
j  com.sun.jna.Function.invoke([Ljava/lang/Object;Ljava/lang/Class;ZI)Ljava/lang/Object;+42
j  com.sun.jna.Function.invoke(Ljava/lang/reflect/Method;[Ljava/lang/Class;Ljava/lang/Class;[Ljava/lang/Object;Ljava/util/Map;)Ljava/lang/Object;+271
j  com.sun.jna.Library$Handler.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;+390
j  jdk.proxy1.$Proxy0.ioctl(ILcom/sun/jna/NativeLong;Lorg/jline/terminal/impl/jna/osx/CLibrary$winsize;)V+27 jdk.proxy1
j  org.jline.terminal.impl.jna.osx.OsXNativePty.getSize()Lorg/jline/terminal/Size;+26
j  org.jline.terminal.impl.AbstractPosixTerminal.getSize()Lorg/jline/terminal/Size;+4
j  org.jline.terminal.Terminal.getBufferSize()Lorg/jline/terminal/Size;+1
j  org.jline.reader.impl.LineReaderImpl.doDisplay()V+8
j  org.jline.reader.impl.LineReaderImpl.<init>(Lorg/jline/terminal/Terminal;Ljava/lang/String;Ljava/util/Map;)V+357
j  org.jline.reader.LineReaderBuilder.build()Lorg/jline/reader/LineReader;+39
j  dotty.tools.repl.JLineTerminal.readLine(Lorg/jline/reader/Completer;Ldotty/tools/dotc/core/Contexts$Context;)Ljava/lang/String;+154
j  dotty.tools.repl.ReplDriver.readLine$1(Ldotty/tools/repl/JLineTerminal;Ldotty/tools/repl/State;)Ldotty/tools/repl/ParseResult;+25
j  dotty.tools.repl.ReplDriver.loop$1(Ldotty/tools/repl/JLineTerminal;Ldotty/tools/repl/State;)Ldotty/tools/repl/State;+3
j  dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(Ldotty/tools/repl/State;Ldotty/tools/repl/JLineTerminal;)Ldotty/tools/repl/State;+3
j  dotty.tools.repl.ReplDriver$$Lambda$278+0x0000000801254768.apply()Ljava/lang/Object;+12
j  dotty.tools.repl.ReplDriver.withRedirectedOutput(Lscala/Function0;)Ldotty/tools/repl/State;+30
j  dotty.tools.repl.ReplDriver.runBody$$anonfun$1(Lscala/Function0;)Ldotty/tools/repl/State;+2
j  dotty.tools.repl.ReplDriver$$Lambda$285+0x0000000801256458.apply()Ljava/lang/Object;+8
j  dotty.tools.runner.ScalaClassLoader$.asContext(Ljava/lang/ClassLoader;Lscala/Function0;)Ljava/lang/Object;+13
j  dotty.tools.repl.ReplDriver.runBody(Lscala/Function0;)Ldotty/tools/repl/State;+21
j  dotty.tools.repl.ReplDriver.runUntilQuit(Ldotty/tools/repl/State;)Ldotty/tools/repl/State;+100
j  dotty.tools.repl.ReplDriver.tryRunning()V+12
j  dotty.tools.repl.Main$.main([Ljava/lang/String;)V+20
j  dotty.tools.repl.Main.main([Ljava/lang/String;)V+4
v  ~StubRoutines::call_stub
```

**Expected behaviour**
- REPL should default to JVM 17 instead of system default
- REPL should not crash or sigsegv
- REPL should return actionable error message to the user on how to fix the problem or how to report the problem
- REPL should allow me to use `scalameta`

### PR DESCRIPTION
**Pull request by Gedochao**
Fixes #2582 

This separates the Scala REPL classpath from user dependencies classpath, preventing clashes and unintended bumps of compiler dependencies.

This also allows to use the recent `jna` version on the Scala REPL with `aarch64` Java releases, for more details read https://github.com/VirtusLab/scala-cli/issues/2582#issuecomment-1833825084

NOTE: this only separates the Scala REPL, and not the Ammonite REPL.
Ammonite REPL does not support a `--classpath` argument.
It would likely be possible to either exclude transitive compiler dependencies in the user dependencies when launching the Ammonite REPL, or preload deps with a script to prevent clashes there, too.
However, as the Ammonite REPL does not have much in terms of dependencies in the first place, this is perhaps not much of an issue, really. 
Isolating the Ammonite REPL classpath is out of the scope of this PR, either way.

### CODE REVIEW

File: modules/build/src/main/scala/scala/build/ReplArtifacts.scala [hunk 1]
```diff
@@ -11,20 +11,19 @@ import scala.build.internal.CsLoggerUtil._
...
-        extraClassPath ++ extraSourceJars ++ replArtifacts.map(_._2)
-      else
-        extraClassPath ++ replArtifacts.map(_._2)
-    cp.distinct
-  }
+  lazy val replClassPath: Seq[os.Path] =
+    (if (addSourceJars)
+       extraClassPath ++ extraSourceJars ++ replArtifacts.map(_._2)
+     else
+       extraClassPath ++ replArtifacts.map(_._2)).distinct
```
Comment (MaciejG604) [inline modules/build/src/main/scala/scala/build/ReplArtifacts.scala]: Shouldn't `distinct` be on both branches of this `if`?

File: modules/build/src/main/scala/scala/build/ReplArtifacts.scala [hunk 2]
```diff
@@ -11,20 +11,19 @@ import scala.build.internal.CsLoggerUtil._
...
-    val cp =
-      if (addSourceJars)
-        extraClassPath ++ extraSourceJars ++ replArtifacts.map(_._2)
-      else
-        extraClassPath ++ replArtifacts.map(_._2)
-    cp.distinct
-  }
+  lazy val replClassPath: Seq[os.Path] =
+    (if (addSourceJars)
+       extraClassPath ++ extraSourceJars ++ replArtifacts.map(_._2)
```
Comment (MaciejG604) [inline modules/build/src/main/scala/scala/build/ReplArtifacts.scala]: While we're at it.
I think extraClassPath contains user dependencies passed as paths to compiled files or jars. What do you think about also passing it with the `--classpath` flag?

File: modules/build/src/main/scala/scala/build/ReplArtifacts.scala (hunk 1 above)
Comment (Gedochao) [reply modules/build/src/main/scala/scala/build/ReplArtifacts.scala]: ...it is.
it's applied to the output to the whole `if`/`else` clause.

Comment (MaciejG604) [reply modules/build/src/main/scala/scala/build/ReplArtifacts.scala]: RIght 😁

File: modules/cli/src/main/scala/scala/cli/commands/repl/Repl.scala [hunk 3]
```diff
@@ -380,16 +380,20 @@ object Repl extends ScalaCommand[ReplOptions] {
       if (dryRun)
         logger.message("Dry run, not running REPL.")
       else {
+        val depClassPathArgs: Seq[String] =
+          if replArtifacts.depsClassPath.nonEmpty then
+            Seq("-classpath", replArtifacts.depsClassPath.map(_.toString).mkString(":"))
```
Comment (tgodzik) [inline modules/cli/src/main/scala/scala/cli/commands/repl/Repl.scala]: Isn't it `;` for windows?

Comment (Gedochao) [reply modules/cli/src/main/scala/scala/cli/commands/repl/Repl.scala]: indeed, good catch

Comment (Gedochao) [reply modules/cli/src/main/scala/scala/cli/commands/repl/Repl.scala]: fixed

File: modules/build/src/main/scala/scala/build/ReplArtifacts.scala (hunk 2 above)
Comment (Gedochao) [reply modules/build/src/main/scala/scala/build/ReplArtifacts.scala]: good call, done

**Review by tgodzik — APPROVED** [review]
LGTM!
