### PR TITLE
Fix generate help for shebang

### LINKED ISSUE #601: Truncated shebang command help description
**Version(s)**

0.1.0

**Describe the bug**

Command-line help for *shebang* command currently states:

```
This command is an equivalent of `run`, but it changes the way how
```

Apparently the description is incomplete and seems to have been truncated.

**To Reproduce**

Run:
```
scala-cli --help
```

Look for the line mentioning the *shebang* command.

**Expected behaviour**

The command description is complete.

### PR DESCRIPTION
**Pull request by lwronski**
Add a shorter description for shebang command in `scala-cli --help`

Replace from 
``` 
shebang    This command is an equivalent of `run`, but it changes the way how
```
to
```
shebang   Like 'run', but more handy from shebang scripts
```

Closes #601

### CODE REVIEW

File: modules/cli/src/main/scala/scala/cli/commands/ShebangOptions.scala [hunk 1]
```diff
@@ -3,7 +3,9 @@ package scala.cli.commands
 import caseapp._
 
 @HelpMessage(
-  """|This command is an equivalent of `run`, but it changes the way how
+  """|Access to command line arguments in shebang scripts
```
Comment (alexarchambault) [inline modules/cli/src/main/scala/scala/cli/commands/ShebangOptions.scala]: I'm not sure about that exact wording… Maybe:
```suggestion
  """|Like 'run', but more handy from shebang scripts
```

File: modules/cli/src/main/scala/scala/cli/commands/ShebangOptions.scala [hunk 2]
```diff
@@ -3,7 +3,9 @@ package scala.cli.commands
...
+     |
+     |This command is an equivalent of `run`, but it changes the way how
```
Comment (alexarchambault) [inline modules/cli/src/main/scala/scala/cli/commands/ShebangOptions.scala]:
```suggestion
     |This command is equivalent to `run`, but it changes the way
```
(no need of "how" here, I think, and not 100% sure, but "equivalent to" sounds better to me)

File: modules/cli/src/main/scala/scala/cli/commands/ShebangOptions.scala [hunk 3]
```diff
@@ -3,7 +3,9 @@ package scala.cli.commands
...
      |`scala-cli` parses it's command-line arguments in order to be compatibility
```
Comment (alexarchambault) [inline modules/cli/src/main/scala/scala/cli/commands/ShebangOptions.scala]:
```suggestion
     |`scala-cli` parses its command-line arguments in order to be compatible
```
(typos)

File: modules/cli/src/main/scala/scala/cli/commands/ShebangOptions.scala (hunk 1 above)
Comment (lwronski) [reply modules/cli/src/main/scala/scala/cli/commands/ShebangOptions.scala]: It sounds better.
