### PR TITLE
Fix ultra-long invalid Scala version errors

### LINKED ISSUE #2722: Excessively long (pages long) output when Scala version not found
```
% scala-cli --version
Scala CLI version: 1.1.2
Scala version (default): 3.3.1
% scala-cli -S 2.13.13-bin-ffc0297
[error]  Cannot find a valid matching Scala version among 2.3.1, 2.3.3, 2.4.0-RC1, 2.4.0-RC2, 2.4.0, 2.5.0-RC1, 2.5.0-RC2, 2.5.0, 2.5.1, 2.6.0-RC2, 2.6.0-RC3, 2.6.0, 2.6.1-rc1, 2.6.1-rc2, 2.6.1, 2.7.0-rc1, 2.7.0-rc2, 2.7.0-rc3, 2.7.0, 2.7.1-rc1, 2.7.1-rc2, 2.7.1, 2.7.2-rc1, 2.7.2-rc2, 2.7.2-rc3, 2.7.2-rc6, 2.7.2, 2.7.3.RC1, 2.7.3.RC2, 2.7.3, 2.7.4.RC1, 2.7.4, 2.7.4.final, 2.7.5, 2.7.6, 2.7.7.RC1, 2.7.7.RC2, 2.7.7, 2.8.0.r18462-b20090811081019, 2.8.0.Beta1-RC1, 2.8.0.Beta1-RC2, 2.8.0.Beta1-RC3, 2.8.0.Beta1-RC4, 2.8.0.Beta1-RC5, 2.8.0.Beta1-RC6, 2.8.0.Beta1-RC7, 2.8.0.Beta1-RC8, 2.8.0.Beta1, 2.8.0.RC1, 2.8.0.RC2, 2.8.0.RC3, 2.8.0.RC4, 2.8.0.RC5, 2.8.0.RC6, 2.8.0.RC7, 2.8.0, 2.8.1.RC1, 2.8.1.RC2, 2.8.1.RC3, 2.8.1.RC4, 2.8.1, 2.8.2.RC1, 2.8.2.RC2, 2.8.2.RC3, 2.8.2, 2.9.0.RC1, 2.9.0.RC2, 2.9.0.RC3, 2.9.0.RC4, 2.9.0.RC5, 2.9.0, 2.9.0-1, 2.9.1.RC1, 2.9.1.RC2, 2.9.1.RC3, 2.9.1.RC4, 2.9.1, 2.9.1-1-RC1, 2.9.1-1, 2.9.2-RC1, 2.9.2-RC2, 2.9.2-RC3, 2.9.2, 2.9.3-RC1, 2.9.3-RC2, 2.9.3, 2.10.0-M1-virtualized.rdev-4217-2012-01-24-g9118644, 2.10.0-M1-virtualized, 2.10.0-M1, 2.10.0-M2, 2.10.0-M3, 2.10.0-M4, 2.10.0-M5, 2.10.0-M6, 2.10.0-M7, 2.10.0-RC1, 2.10.0-RC2, 2.10.0-RC3, 2.10.0-RC4, 2.10.0-RC5, 2.10.0, 2.10.1-RC1, 2.10.1-RC2, 2.10.1-RC3, 2.10.1, 2.10.2-RC1, 2.10.2-RC2, 2.10.2, 2.10.3-RC1, 2.10.3-RC2, 2.10.3-RC3, 2.10.3, 2.10.4-RC1, 2.10.4-RC2, 2.10.4-RC3, 2.10.4, 2.10.5, 2.10.6, 2.10.7, 2.11.0-M1, 2.11.0-M2, 2.11.0-M3, 2.11.0-M4, 2.11.0-M5, 2.11.0-M6, 2.11.0-M7, 2.11.0-M8, 2.11.0-RC1, 2.11.0-RC3, 2.11.0-RC4, 2.11.0, 2.11.1, 2.11.2, 2.11.3, 2.11.4, 2.11.5, 2.11.6, 2.11.7, 2.11.8, 2.11.8-18269ea, 2.11.9, 2.11.9-bin-03d5f4e, 2.11.9-bin-3f437a2, 2.11.9-bin-8d16a0b, 2.11.9-bin-42f813e, 2.11.9-bin-99f41a1, 2.11.9-bin-363d9e5, 2.11.9-bin-828a892, 2.11.10, 2.11.10-bin-d9150aa, 2.11.10-bin-7fa3823, 2.11.10-bin-94dd1dc, 2.11.10-bin-6008e4b, 2.11.11, 2.11.11-bin-a3987d8, 2.11.11-bin-7a5df57, 2.11.11-bin-8a413ba, 2.11.11-bin-5167b69, 2.11.12, 2.11.12-bin-ad19744, 2.11.12-bin-d37ff07, 2.11.12-bin-d209ff4, 2.11.12-bin-e877349, 2.11.12-bin-eec9e69, 2.11.12-bin-efd31ff, 2.11.12-bin-f3419fc, 2.11.12-bin-b8155a5, 2.11.12-bin-2e2f65a, 2.11.12-bin-3fd7aec, 2.11.12-bin-4b1f621, 2.11.12-bin-009e59a, 2.11.12-bin-18f625d, 2.11.12-bin-60e8173, 2.11.12-bin-73b4d40, 2.11.12-bin-790de6d, 2.11.12-bin-6909e6d, 2.11.12-bin-4930995, 2.12.0-M1, 2.12.0-M2, 2.12.0-M3-dc9effe, 2.12.0-M3, 2.12.0-M4, 2.12.0-M4-9901daf, 2.12.0-M5, 2.12.0-pre-ceaf419, 2.12.0-pre-d90d8b8, 2.12.0-pre-fdb3105, 2.12.0-pre-1e81a09, 2.12.0-pre-9d3f077, 2.12.0-pre-50fca2d, 2.12.0-pre-95b1427, 2.12.0-pre-510d8ef, 2.12.0-pre-933bab2, 2.12.0-pre-1615ce9, 2.12.0-pre-05016d9, 2.12.0-RC1-be43eb5, 2.12.0-RC1-ceaf419, 2.12.0-RC1, 2.12.0-RC1-1e81a09, 2.12.0-RC2, 2.12.0, 2.12.1, 2.12.1-bin-fc1aea6, 2.12.1-bin-92b695c, 2.12.1-bin-208faa7, 2.12.2, 2.12.2-bin-aa9a627, 2.12.2-bin-c4cdf0e, 2.12.2-bin-c7c2152, 2.12.2-bin-c8b8005, 2.12.2-bin-c309f98, 2.12.2-bin-cba77ce, 2.12.2-bin-cbf7daa, 2.12.2-bin-cc7acdd, 2.12.2-bin-d0c2620, 2.12.2-bin-d1d700e, 2.12.2-bin-d5aad25, 2.12.2-bin-d9c3bd5, 2.12.2-bin-d6837ae, 2.12.2-bin-d61301d, 2.12.2-bin-db8520e, 2.12.2-bin-e2aaf2c, 2.12.2-bin-ecf3fa6, 2.12.2-bin-ed9352a, 2.12.2-bin-ee5ca5d, 2.12.2-bin-effde0c, 2.12.2-bin-f2c6005, 2.12.2-bin-f2e05c2, 2.12.2-bin-f5ce29b, 2.12.2-bin-f174bfb, 2.12.2-bin-f9514bb, 2.12.2-bin-f771395, 2.12.2-bin-a8c4a54, 2.12.2-bin-a21daec, 2.12.2-bin-b68cc6c, 2.12.2-bin-0dab108, 2.12.2-bin-0e38f28, 2.12.2-bin-0f1b635, 2.12.2-bin-1ef37f0, 2.12.2-bin-1b4d36f, 2.12.2-bin-2ba0530, 2.12.2-bin-02a240a, 2.12.2-bin-3fadf69, 2.12.2-bin-4dc194d, 2.12.2-bin-4efab51, 2.12.2-bin-05d5338, 2.12.2-bin-5f1a638, 2.12.2-bin-5a2e406, 2.12.2-bin-6e9268b, 2.12.2-bin-6f905fd, 2.12.2-bin-7b9d3cc, 2.12.2-bin-7b45676, 2.12.2-bin-8e40bef, 2.12.2-bin-12c240d, 2.12.2-bin-15e2759, 2.12.2-bin-17e057b, 2.12.2-bin-21d12e9, 2.12.2-bin-023a96a, 2.12.2-bin-38baf2b, 2.12.2-bin-60d01de, 2.12.2-bin-82b2470, 2.12.2-bin-95a263e, 2.12.2-bin-96cdfb4, 2.12.2-bin-96a7617, 2.12.2-bin-197bb9e, 2.12.2-bin-232d95a, 2.12.2-bin-567aa14, 2.12.2-bin-575c342, 2.12.2-bin-680d866, 2.12.2-bin-715c88e, 2.12.2-bin-759a7b7, 2.12.2-bin-920bc4e, 2.12.2-bin-2261f3e, 2.12.2-bin-6048c66, 2.12.2-bin-18157b9, 2.12.2-bin-57948c8, 2.12.2-bin-482879f, 2.12.2-bin-8513577, 2.12.3, 2.12.3-bin-ae9b465, 2.12.3-bin-af353e0, 2.12.3-bin-ba9dacc, 2.12.3-bin-ba881ae, 2.12.3-bin-bb723dd, 2.12.3-bin-bb60167, 2.12.3-bin-bd6294d, 2.12.3-bin-befd633, 2.12.3-bin-c0f98ac, 2.12.3-bin-c4a732e, 2.12.3-bin-c8d84ef, 2.12.3-bin-c9c5cfd, 2.12.3-bin-c48b1bc, 2.12.3-bin-c84ea81, 2.12.3-bin-c331c78, 2.12.3-bin-c487779, 2.12.3-bin-cc7ba86, 2.12.3-bin-ccbf27e, 2.12.3-bin-ccfba35, 2.12.3-bin-ce0e5b2, 2.12.3-bin-d1ec01a, 2.12.3-bin-d56fb2a, 2.12.3-bin-d201b5d, 2.12.3-bin-db80860, 2.12.3-bin-ddf4e2c, 2.12.3-bin-de9c93a, 2.12.3-bin-e2dc0de, 2.12.3-bin-e5be62d, 2.12.3-bin-e6bfbca, 2.12.3-bin-e7dd229, 2.12.3-bin-e53c0d3, 2.12.3-bin-e72ab5a, 2.12.3-bin-e76c3df, 2.12.3-bin-f35ab66, 2.12.3-bin-f079ff7, 2.12.3-bin-ff57fa8, 2.12.3-bin-a3ec4a0, 2.12.3-bin-a5c663a, 2.12.3-bin-a6e7134, 2.12.3-bin-a35c3c9, 2.12.3-bin-a840dc9, 2.12.3-bin-a610630, 2.12.3-bin-b5fc0ca, 2.12.3-bin-b69ed17, 2.12.3-bin-0c3e73b, 2.12.3-bin-0dc2c3d, 2.12.3-bin-0a01e0b, 2.12.3-bin-0b150b7, 2.12.3-bin-2c50123, 2.12.3-bin-2f52c61, 2.12.3-bin-3a4ac96, 2.12.3-bin-3b4f329, 2.12.3-bin-4c5772d, ...
You can only choose one of the 3.x, 2.13.x, and 2.12.x. versions.
The latest supported stable versions are 2.12.18, 2.13.12, 3.3.1.
In addition, you can request compilation with the last nightly versions of Scala,
by passing the 2.nightly, 2.12.nightly, 2.13.nightly, or 3.nightly arguments.
Specific Scala 2 or Scala 3 nightly versions are also accepted.
```

and getting longer every day :D

it's so long I had to truncate it here, because GitHub said "Comment is too long (maximum is 65536 characters)"

### PR DESCRIPTION
**Pull request by Gedochao**
Fixes #2722 

The errors should get down to reasonable lengths from now on.

```bash
scala-cli -S 2.13.13-bin-ffc0292
# [error]  Cannot find a valid matching Scala version for 2.13.13-bin-ffc0292.
# You can only choose one of the 3.x, 2.13.x, and 2.12.x. versions.
# The latest supported stable versions are 2.12.18, 2.13.12, 3.3.1.
# In addition, you can request compilation with the last nightly versions of Scala,
# by passing the 2.nightly, 2.12.nightly, 2.13.nightly, or 3.nightly arguments.
# Specific Scala 2 or Scala 3 nightly versions are also accepted.
# You can also request the latest Scala 3 LTS by passing lts or 3.lts.
```

### CODE REVIEW

File: modules/core/src/main/scala/scala/build/errors/NoValidScalaVersionFoundError.scala [hunk 1]
```diff
@@ -1,7 +1,12 @@
...
+    extends ScalaVersionError({
+      val suffix = if versionString.nonEmpty then s" for $versionString" else ""
+      s"Cannot find a valid matching Scala version$suffix."
+    })
 
-final class NoValidScalaVersionFoundError(val foundVersions: Seq[String]) extends ScalaVersionError(
-      s"Cannot find a valid matching Scala version among ${foundVersions.mkString(", ")}"
-    )
+object NoValidScalaVersionFoundError {
+  def apply(versionString: String = ""): NoValidScalaVersionFoundError =
```
Comment (kasiaMarek) [inline modules/core/src/main/scala/scala/build/errors/NoValidScalaVersionFoundError.scala]: Maybe just add default value to constructor instead?

**Review by kasiaMarek — APPROVED** [review]

File: modules/core/src/main/scala/scala/build/errors/NoValidScalaVersionFoundError.scala (hunk 1 above)
Comment (Gedochao) [reply modules/core/src/main/scala/scala/build/errors/NoValidScalaVersionFoundError.scala]: Hey, y're right. 
Not sure why I did that.
Fixed, anyway.
