### PR TITLE
Adjust Scala CLI nightly version resolution for the new Maven Central Snapshots repository

### LINKED ISSUE #3742: New nightlies aren't being published to Sonatype Central
**Version(s)**
1.8.1
1.8.1-17-gd48c691a8-SNAPSHOT

**Describe the bug**
It seems usage of `--cli-version nightly` no longer works as intended, after we migrated publishing to Sonatype Central Portal.

**To Reproduce**
`--cli-version nightly` points to an old version.
```scala
scala-cli --cli-version nightly -e 'println("Hello")' --native 
Fetching Scala CLI 1.8.1-1-gc0e412a9a-SNAPSHOT
Downloading compiler plugin org.scala-native:::nscplugin:0.5.7
Downloading 2 dependencies
Compiling project (Scala 3.7.1, Scala Native 0.5.7)
Compiled project (Scala 3.7.1, Scala Native 0.5.7)
...
```
1.8.1-17-gd48c691a8-SNAPSHOT got released sufficiently earlier (also notice that it's the 17th nightly after 1.8.1): https://github.com/VirtusLab/scala-cli/actions/runs/15588192852/job/43929147790#step:6:470

Pointing to the new nightly version explicitly also fails:
```scala
scala-cli --cli-version 1.8.1-17-gd48c691a8-SNAPSHOT -e 'println("Hello")' --native
Fetching Scala CLI 1.8.1-17-gd48c691a8-SNAPSHOT
Error downloading org.virtuslab.scala-cli:cli_3:1.8.1-17-gd48c691a8-SNAPSHOT
  not found: https://repo1.maven.org/maven2/org/virtuslab/scala-cli/cli_3/1.8.1-17-gd48c691a8-SNAPSHOT/cli_3-1.8.1-17-gd48c691a8-SNAPSHOT.pom
  not found: https://oss.sonatype.org/content/repositories/snapshots/org/virtuslab/scala-cli/cli_3/1.8.1-17-gd48c691a8-SNAPSHOT/cli_3-1.8.1-17-gd48c691a8-SNAPSHOT.pom
  No fallback URL found
  not found: /Users/pchabelski/.ivy2/local/org.virtuslab.scala-cli/cli_3/1.8.1-17-gd48c691a8-SNAPSHOT/ivys/ivy.xml
```

**Expected behaviour**
I'd expect the new nightlies to be available under `--cli-version` and picked up automatically.

### PR DESCRIPTION
**Pull request by Gedochao**
fixes https://github.com/VirtusLab/scala-cli/issues/3742

```bash
scala-cli --cli-version nightly version 
# Scala CLI version: 1.8.4-20-g9136c9b3a-SNAPSHOT
# Scala version (default): 3.7.2
```

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]

File: modules/cli/src/main/scala/scala/cli/launcher/LauncherCli.scala [hunk 1]
```diff
@@ -61,47 +60,43 @@ object LauncherCli {
...
     cache: FileCache[Task],
-    scalaParameters: ScalaParameters
+    scalaBinaryVersion: String
   ): String = {
-
-    val snapshotRepoUrl =
-      s"https://oss.sonatype.org/content/repositories/snapshots/org/virtuslab/scala-cli/cli_${scalaParameters.scalaBinaryVersion}/"
-    val artifact = Artifact(snapshotRepoUrl).withChanging(true)
+    val cliSubPath       = s"org/virtuslab/scala-cli/cli_$scalaBinaryVersion"
+    val mavenMetadataUrl = s"${SonatypeUtils.snapshotsRepositoryUrl}/$cliSubPath/maven-metadata.xml"
```
Comment (tgodzik) [inline modules/cli/src/main/scala/scala/cli/launcher/LauncherCli.scala:86]: Och, at least the new snapshots have maven metadata.

**Review by tgodzik — APPROVED** [review]
LGTM

File: modules/cli/src/main/scala/scala/cli/launcher/LauncherCli.scala (hunk 1 above)
Comment (Gedochao) [reply modules/cli/src/main/scala/scala/cli/launcher/LauncherCli.scala:86]: the old ones do as well, actually.
so this solution works for either.
