### PR TITLE
Suggest user to update scala-cli by package manager in doctor

### LINKED ISSUE #1038: Confusing message about managing itself with doctor
**Version(s)**

0.1.6

**Describe the bug**

Not really a bug, but I think this might lead to a bit of confusion as it confused me a bit. When I try the `scala-cli doctor` command I see this message.

```
❯ scala-cli doctor
Your scala-cli version (0.1.6) is current.
scala-cli could update itself since it is correctly installed in only one location: Set(/Users/ckipp/Library/Application Support/Coursier/bin/scala-cli).
Your scala-cli is a native application.
```

I'm not really sure why it tells me the part about how scala-cli could update itself. I use `cs` to manage scala-cli but I was curious what would happen if I do a `scala-cli update`, since that's what the message makes it sound like I can do.

When I do that I get:

```
❯ scala-cli update
Scala CLI was not installed by the installation script, please use your package manager to update scala-cli.
```

These two messages seem at odds with one another. If I'm using a tool like `cs` to manage scala-cli I shouldn't see a message about using itself to update.

**To Reproduce**
Follow the steps above.

**Expected behaviour**
Clear messages.

### PR DESCRIPTION
**Pull request by lwronski**

### CODE REVIEW

File: modules/cli/src/main/scala/scala/cli/commands/Doctor.scala [hunk 1]
```diff
@@ -67,10 +67,15 @@ object Doctor extends ScalaCommand[DoctorOptions] {
...
         s"scala-cli would not be able to update itself since it is installed in multiple directories: ${scalaCliPaths.mkString(", ")}."
       )
-    else
+    else if (Update.isScalaCLIInstalledByInstallationScript())
       println(
         s"scala-cli could update itself since it is correctly installed in only one location: $scalaCliPaths."
       )
+    else
+      println(
+        s"scala-cli could update by your package manager since it is correctly installed in only one location: $scalaCliPaths."
```
Comment (alexarchambault) [inline modules/cli/src/main/scala/scala/cli/commands/Doctor.scala]: NIT Phrasing, and don't leave `Seq(…)` or `List(…)` in the output.
```suggestion
        s"scala-cli can be updated by your package manager since it is correctly installed in only one location: ${scalaCliPaths.mkString}."
```

Comment (alexarchambault) [reply modules/cli/src/main/scala/scala/cli/commands/Doctor.scala]: Ideally, we should implement https://github.com/VirtusLab/scala-cli/issues/670#issuecomment-1123664191, and rely on it to know whether the `scala-cli` binary has been installed by a package manager.

**Review by alexarchambault — APPROVED** [review]
