### PR TITLE
Fix using directives crashing on `*/` by removing `/* (..) */` comments support in `using_directives`

### LINKED ISSUE #3374: `using_directives` parser crashes on `*/*/Foo.scala`
**Version(s)**
1.5.4

**Describe the bug**
Using a nested wildcard (`*/*/...`) in `exclude` directive results in a crash caused by `java.lang.ArrayIndexOutOfBoundsException`

**To Reproduce**
Having the following project structure:
* ./project.scala:
```scala
//> using exclude */*/Foo.scala
```

* ./dir1/dir2/Foo.scala:
```scala
val foo // invalid code
```
Try to compile the project:
```shell
scala-cli compile .
```
**Expected behaviour**
Should not crash. Also the invalid file `Foo.scala` should be excluded from compilation sources and the compilation should succeed

### PR DESCRIPTION
**Pull request by Gedochao**
Fixes #3374 

Requires:
- [x] https://github.com/VirtusLab/using_directives/pull/67

### CODE REVIEW

File: modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala [hunk 1]
```diff
@@ -720,4 +720,20 @@ abstract class CompileTestDefinitions
       expect(buildTargetDirs.size == 2)
     }
   }
+
+  if (!Properties.isWin)
+    // TODO: make this work on Windows
```
Comment (Gedochao) [inline modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala]: - likely the same problem as https://github.com/VirtusLab/scala-cli/issues/2973, let's track it there

Comment (tgodzik) [reply modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala]: We should attach it to the TODO

**Review by tgodzik — APPROVED** [review]
LGTM

File: modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala (hunk 1 above)
Comment (Gedochao) [reply modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala]: sure, added the ticket link to the comment
