### PR TITLE
Make dependencies keep their positions when fetching

### LINKED ISSUE #2179: Error message for the using directive is misleading.
**Version(s)**
1.0.0

**Describe the bug**
If there is one incorrectly defined directive `dep`, the following directives are also reported as incorrect, even though they are valid.

**To Reproduce**
```
$ cat Hello.scala
//> using scala "3.2.2"
//> using dep "org.xyz::foo:0.0.1"
//> using dep "com.lihaoyi::upickle:3.1.0"
$ scala-cli compile Hello.scala
Downloading 3 dependencies
[error] ./Hello.scala:2:16
[error] Error downloading org.xyz:foo_3:0.0.1
[error]   not found: /Users/lwronski/.ivy2/local/org.xyz/foo_3/0.0.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/xyz/foo_3/0.0.1/foo_3-0.0.1.pom
[error]   not found: /Users/lwronski/Library/Caches/ScalaCli/local-repo/v1.0.0/org.xyz/foo_3/0.0.1/ivys/ivy.xml
[error]   No fallback URL found
[error] //> using dep "org.xyz::foo:0.0.1"
[error]                ^^^^^^^^^^^^^^^^^^
[error] ./Hello.scala:3:16
[error] Error downloading org.xyz:foo_3:0.0.1
[error]   not found: /Users/lwronski/.ivy2/local/org.xyz/foo_3/0.0.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/xyz/foo_3/0.0.1/foo_3-0.0.1.pom
[error]   not found: /Users/lwronski/Library/Caches/ScalaCli/local-repo/v1.0.0/org.xyz/foo_3/0.0.1/ivys/ivy.xml
[error]   No fallback URL found
[error] //> using dep "com.lihaoyi::upickle:3.1.0"
[error]                ^^^^^^^^^^^^^^^^^^^^^^^^^^
```
**Expected behaviour**
It should not print that the directive `"//> using dep "com.lihaoyi::upickle:3.1.0"` is incorrect

### PR DESCRIPTION
**Pull request by MaciejG604**
And add ResolutionError handling.
Fixes #2179

### CODE REVIEW

File: modules/build/src/test/scala/scala/build/tests/DirectiveTests.scala [hunk 1]
```diff
@@ -421,4 +426,46 @@ class DirectiveTests extends munit.FunSuite {
         }
     }
   }
+
+  test("dependency resolution errors with positions") {
+    val testInputs = TestInputs(
+      os.rel / "simple.sc" ->
+        """//> using dep org.xyz::foo:0.0.1
+          |//> using dep org.qwerty::bar:0.0.1
```
Comment (lwronski) [inline modules/build/src/test/scala/scala/build/tests/DirectiveTests.scala]: Add correct dependency here to ensure the warning message, indicating the dependency can't be downloaded, is no longer displayed.

**Review by lwronski — APPROVED** [review]
LGTM
