### PR TITLE
Suggest users to clean working directory when Nailgun server failed

### LINKED ISSUE #1882: scala-cli fails to start with a "bloop server failed to start" error message
**Version(s)**
0.1.20

**Describe the bug**
When attempting to execute code with scala-cli, it fails with:
```
[E] Failed to load project from /path/to/wd/scala-build/.bloop/project_724f53bbeb-402a56f8c4.json
Error: java.lang.RuntimeException: Bloop BSP connection in /home/nrinaudo/.cache/scalacli/bsp-sockets/proc-304411 was unexpectedly closed or bloop didn't start.
For more details, please see '/path/to/wd/scala-build/stacktraces/1677076006-2251002204469956629.log'
```
I've included a more complete error log at the end of this.

**To Reproduce**
Attempt to run Scala 3 code via a command such a:
```
scala-cli ./file.sc
```

**Expected behaviour**
I would expect not to get a bloop related error.

**Complete error log**
This was obtained using `-v -v -v`:
```
Fetching List(Dependency(org.scala-lang:scala3-compiler_3, 3.2.2, Configuration(), Set(), Publication(, Type(), Extension(), Classifier()), false, true)), adding List(IvyRepository(Pattern(List(Const(file:///home/nrinaudo/.cache/scalacli/local-repo/v0.1.20//), Var(organisation), Const(/), Var(module), Const(/), Opt(List(Const(scala_), Var(scalaVersion), Const(/))), Opt(List(Const(sbt_), Var(sbtVersion), Const(/))), Var(revision), Const(/), Var(type), Const(s/), Var(artifact), Opt(List(Const(-), Var(classifier))), Const(.), Var(ext))), None, None, true, true, true, false, None, true))
Found 13 artifacts:
  /home/nrinaudo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.2.2/scala3-compiler_3-3.2.2.jar
  /home/nrinaudo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.2.2/scala3-interfaces-3.2.2.jar
  /home/nrinaudo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.2.2/scala3-library_3-3.2.2.jar
  /home/nrinaudo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.2.2/tasty-core_3-3.2.2.jar
  /home/nrinaudo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.3.0-scala-1/scala-asm-9.3.0-scala-1.jar
  /home/nrinaudo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.3.5/compiler-interface-1.3.5.jar
  /home/nrinaudo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-reader/3.19.0/jline-reader-3.19.0.jar
  /home/nrinaudo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-terminal/3.19.0/jline-terminal-3.19.0.jar
  /home/nrinaudo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-terminal-jna/3.19.0/jline-terminal-jna-3.19.0.jar
  /home/nrinaudo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar
  /home/nrinaudo/.cache/coursier/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.7.0/protobuf-java-3.7.0.jar
  /home/nrinaudo/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/util-interface/1.3.0/util-interface-1.3.0.jar
  /home/nrinaudo/.cache/coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar

Fetching List(Dependency(org.scala-lang:scala3-library_3, 3.2.2, Configuration(), Set(), Publication(, Type(), Extension(), Classifier()), false, true)), adding List(IvyRepository(Pattern(List(Const(file:///home/nrinaudo/.cache/scalacli/local-repo/v0.1.20//), Var(organisation), Const(/), Var(module), Const(/), Opt(List(Const(scala_), Var(scalaVersion), Const(/))), Opt(List(Const(sbt_), Var(sbtVersion), Const(/))), Var(revision), Const(/), Var(type), Const(s/), Var(artifact), Opt(List(Const(-), Var(classifier))), Const(.), Var(ext))), None, None, true, true, true, false, None, true))
Fetching List(Dependency(org.virtuslab.scala-cli:stubs, 0.1.20, Configuration(), Set(), Publication(, Type(), Extension(), Classifier()), false, true)), adding List(IvyRepository(Pattern(List(Const(file:///home/nrinaudo/.cache/scalacli/local-repo/v0.1.20//), Var(organisation), Const(/), Var(module), Const(/), Opt(List(Const(scala_), Var(scalaVersion), Const(/))), Opt(List(Const(sbt_), Var(sbtVersion), Const(/))), Var(revision), Const(/), Var(type), Const(s/), Var(artifact), Opt(List(Const(-), Var(classifier))), Const(.), Var(ext))), None, None, true, true, true, false, None, true))
Found 1 artifacts:
  /home/nrinaudo/.cache/scalacli/local-repo/v0.1.20/org.virtuslab.scala-cli/stubs/0.1.20/jars/stubs.jar

Checking for a running Bloop server at /home/nrinaudo/.local/share/scalacli/bloop/daemon ...
Attempting to connect to Bloop server /home/nrinaudo/.local/share/scalacli/bloop/daemon ...
Connection attempt result: Some(Right(java.nio.channels.SocketChannel[connected local= remote=/home/nrinaudo/.local/share/scalacli/bloop/daemon/socket]))
nailgun debug: Sending arguments '' to Nailgun server
nailgun debug: Sending environment variables to Nailgun server
nailgun debug: Sending working directory /home/nrinaudo/dev/nrinaudo/test to Nailgun server
nailgun debug: Sending command to about Nailgun server
nailgun debug: Finished sending command information to Nailgun server
nailgun debug: Starting thread to read stdin...
nailgun debug: Received action Print([B@2367a06c) from Nailgun server
nailgun debug: Received action Print([B@1779b229) from Nailgun server
nailgun debug: Received action Print([B@551c38de) from Nailgun server
nailgun debug: Received action Print([B@7f721d2) from Nailgun server
nailgun debug: Received action Print([B@2d4acc61) from Nailgun server
nailgun debug: Received action Print([B@699869e3) from Nailgun server
nailgun debug: Received action Exit(0) from Nailgun server
nailgun debug: Waiting for stdin thread to finish...
nailgun debug: Waiting for heartbeat thread to finish...
nailgun debug: Returning exit code...
Checking for a running Bloop server at /home/nrinaudo/.local/share/scalacli/bloop/daemon ...
Attempting to connect to Bloop server /home/nrinaudo/.local/share/scalacli/bloop/daemon ...
Connection attempt result: Some(Right(java.nio.channels.SocketChannel[connected local= remote=/home/nrinaudo/.local/share/scalacli/bloop/daemon/socket]))
Checking for a running Bloop server at /home/nrinaudo/.local/share/scalacli/bloop/daemon ...
Attempting to connect to Bloop server /home/nrinaudo/.local/share/scalacli/bloop/daemon ...
Connection attempt result: Some(Right(java.nio.channels.SocketChannel[connected local= remote=/home/nrinaudo/.local/share/scalacli/bloop/daemon/socket]))
nailgun debug: Sending arguments '' to Nailgun server
nailgun debug: Sending environment variables to Nailgun server
nailgun debug: Sending working directory /home/nrinaudo/dev/nrinaudo/test to Nailgun server
nailgun debug: Sending command to about Nailgun server
nailgun debug: Finished sending command information to Nailgun server
nailgun debug: Starting thread to read stdin...
nailgun debug: Received action Print([B@78777449) from Nailgun server
nailgun debug: Received action Print([B@15836fd0) from Nailgun server
nailgun debug: Received action Print([B@51926cb) from Nailgun server
nailgun debug: Received action Print([B@53cec9e4) from Nailgun server
nailgun debug: Received action Print([B@10553749) from Nailgun server
nailgun debug: Received action Print([B@677f53fa) from Nailgun server
nailgun debug: Received action Exit(0) from Nailgun server
nailgun debug: Waiting for stdin thread to finish...
nailgun debug: Waiting for heartbeat thread to finish...
nailgun debug: Returning exit code...
Opening BSP connection with bloop
Bloop BSP connection waiting at local:/home/nrinaudo/.cache/scalacli/bsp-sockets/proc-306146
BSP connection at /home/nrinaudo/.cache/scalacli/bsp-sockets/proc-306146 not found, waiting 100 milliseconds
nailgun debug: Sending arguments '--protocol local --socket /home/nrinaudo/.cache/scalacli/bsp-sockets/proc-306146' to Nailgun server
nailgun debug: Sending environment variables to Nailgun server
nailgun debug: Sending working directory /home/nrinaudo/dev/nrinaudo/test/.scala-build to Nailgun server
nailgun debug: Sending command to bsp Nailgun server
nailgun debug: Finished sending command information to Nailgun server
nailgun debug: Starting thread to read stdin...
nailgun debug: Received action Print([B@2f9cff45) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.2.0/scala3-compiler_3-3.2.0.jar doesn't exist!
nailgun debug: Received action Print([B@42403e58) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.2.0/scala3-interfaces-3.2.0.jar doesn't exist!
nailgun debug: Received action Print([B@6b75866f) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.2.0/scala3-library_3-3.2.0.jar doesn't exist!
nailgun debug: Received action Print([B@575dc8ee) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.2.0/tasty-core_3-3.2.0.jar doesn't exist!
nailgun debug: Received action Print([B@f438928) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.2.0/scala3-compiler_3-3.2.0.jar doesn't exist!
nailgun debug: Received action Print([B@6d4b76fb) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.3.0-scala-1/scala-asm-9.3.0-scala-1.jar doesn't exist!
nailgun debug: Received action Print([B@5054ebab) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.3.5/compiler-interface-1.3.5.jar doesn't exist!
nailgun debug: Received action Print([B@49a08cbb) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.2.0/scala3-interfaces-3.2.0.jar doesn't exist!
nailgun debug: Received action Print([B@690a8dfc) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-reader/3.19.0/jline-reader-3.19.0.jar doesn't exist!
nailgun debug: Received action Print([B@39485bef) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.2.0/scala3-library_3-3.2.0.jar doesn't exist!
nailgun debug: Received action Print([B@4332068) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-terminal/3.19.0/jline-terminal-3.19.0.jar doesn't exist!
nailgun debug: Received action Print([B@56e9539a) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.2.0/tasty-core_3-3.2.0.jar doesn't exist!
nailgun debug: Received action Print([B@1a02ef7f) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-terminal-jna/3.19.0/jline-terminal-jna-3.19.0.jar doesn't exist!
nailgun debug: Received action Print([B@45a234b0) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.3.0-scala-1/scala-asm-9.3.0-scala-1.jar doesn't exist!
nailgun debug: Received action Print([B@95e6652) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar doesn't exist!
nailgun debug: Received action Print([B@2f5e7af8) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.3.5/compiler-interface-1.3.5.jar doesn't exist!
nailgun debug: Received action Print([B@271b2504) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.7.0/protobuf-java-3.7.0.jar doesn't exist!
nailgun debug: Received action Print([B@616496ce) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-reader/3.19.0/jline-reader-3.19.0.jar doesn't exist!
nailgun debug: Received action Print([B@1eccf302) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/util-interface/1.3.0/util-interface-1.3.0.jar doesn't exist!
nailgun debug: Received action Print([B@53dec294) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.2.1/scala3-compiler_3-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@316c8f9b) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar doesn't exist!
nailgun debug: Received action Print([B@41ea3217) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-terminal/3.19.0/jline-terminal-3.19.0.jar doesn't exist!
nailgun debug: Received action Print([B@726167c9) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-terminal-jna/3.19.0/jline-terminal-jna-3.19.0.jar doesn't exist!
nailgun debug: Received action Print([B@455a0d6a) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.2.1/scala3-interfaces-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@514ff1a5) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.2.1/scala3-compiler_3-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@4ca6e96b) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar doesn't exist!
nailgun debug: Received action Print([B@71f478b1) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.2.1/scala3-compiler_3-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@665a13fb) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.2.1/scala3-library_3-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@2d53c639) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.2.1/scala3-interfaces-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@24d5950b) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.2.1/tasty-core_3-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@3590fc34) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.2.1/scala3-compiler_3-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@6724bdb7) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.7.0/protobuf-java-3.7.0.jar doesn't exist!
nailgun debug: Received action Print([B@2daa71cb) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.2.1/scala3-interfaces-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@2b8f67cf) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/util-interface/1.3.0/util-interface-1.3.0.jar doesn't exist!
nailgun debug: Received action Print([B@4d7f8057) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.2.1/scala3-library_3-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@c1adabe) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.2.0/scala3-compiler_3-3.2.0.jar doesn't exist!
nailgun debug: Received action Print([B@5069da3b) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.2.1/scala3-interfaces-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@4d4f7c89) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.2.1/scala3-compiler_3-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@4daca884) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.3.0-scala-1/scala-asm-9.3.0-scala-1.jar doesn't exist!
nailgun debug: Received action Print([B@2447a9c9) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.2.1/scala3-library_3-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@295f84c8) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.3.5/compiler-interface-1.3.5.jar doesn't exist!
nailgun debug: Received action Print([B@33908223) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-reader/3.19.0/jline-reader-3.19.0.jar doesn't exist!
nailgun debug: Received action Print([B@39a06e73) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-terminal/3.19.0/jline-terminal-3.19.0.jar doesn't exist!
nailgun debug: Received action Print([B@2428c3c6) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.2.1/scala3-interfaces-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@2a5f0302) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.2.1/scala3-library_3-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@2639bf8) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.2.0/scala3-interfaces-3.2.0.jar doesn't exist!
nailgun debug: Received action Print([B@1a795620) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.2.1/tasty-core_3-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@553ab324) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar doesn't exist!
nailgun debug: Received action Print([B@4952b3bd) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.3.0-scala-1/scala-asm-9.3.0-scala-1.jar doesn't exist!
nailgun debug: Received action Print([B@7ba5f42e) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.2.0/scala3-compiler_3-3.2.0.jar doesn't exist!
nailgun debug: Received action Print([B@2ac41e7d) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.2.0/scala3-library_3-3.2.0.jar doesn't exist!
nailgun debug: Received action Print([B@6b098a9) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.2.0/scala3-interfaces-3.2.0.jar doesn't exist!
nailgun debug: Received action Print([B@67c1d472) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.2.1/tasty-core_3-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@37ed58bc) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.2.1/scala3-library_3-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@60caa573) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline-terminal-jna/3.19.0/jline-terminal-jna-3.19.0.jar doesn't exist!
nailgun debug: Received action Print([B@32cd6dc7) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.2.1/tasty-core_3-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@75cb427d) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar doesn't exist!
nailgun debug: Received action Print([B@12720e2e) from Nailgun server
[E] Failed to load project from /home/nrinaudo/dev/nrinaudo/test/.scala-build/.bloop/project_103be31561-402a56f8c4.json
nailgun debug: Received action Print([B@39345e49) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.2.1/tasty-core_3-3.2.1.jar doesn't exist!
nailgun debug: Received action Print([B@38d37961) from Nailgun server
[W] Scala instance jar /home/nicolas/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.3.0-scala-1/scala-asm-9.3.0-scala-1.jar doesn't exist!
nailgun debug: Received action Exit(1) from Nailgun server
nailgun debug: Waiting for stdin thread to finish...
nailgun debug: Waiting for heartbeat thread to finish...
nailgun debug: Returning exit code...
Exception in thread "main" java.lang.RuntimeException: Bloop BSP connection in /home/nrinaudo/.cache/scalacli/bsp-sockets/proc-306146 was unexpectedly closed or bloop didn't start.
	at scala.sys.package$.error(package.scala:27)
	at scala.build.blooprifle.internal.Operations$$anon$1.openSocket(Operations.scala:390)
	at scala.build.bloop.BloopServer$.create$1(BloopServer.scala:126)
	at scala.build.bloop.BloopServer$.connect(BloopServer.scala:142)
	at scala.build.bloop.BloopServer$.bsp(BloopServer.scala:165)
	at scala.build.bloop.BloopServer$.buildServer(BloopServer.scala:184)
	at scala.build.compiler.BloopCompilerMaker.$anonfun$1(BloopCompilerMaker.scala:32)
	at scala.build.compiler.BloopCompiler.<init>(BloopCompiler.scala:13)
	at scala.build.compiler.BloopCompilerMaker.create(BloopCompilerMaker.scala:34)
	at scala.build.compiler.BloopCompilerMaker.create(BloopCompilerMaker.scala:16)
	at scala.build.compiler.ScalaCompilerMaker.withCompiler(ScalaCompilerMaker.scala:29)
	at scala.build.compiler.ScalaCompilerMaker.withCompiler$(ScalaCompilerMaker.scala:7)
	at scala.build.compiler.BloopCompilerMaker.withCompiler(BloopCompilerMaker.scala:11)
	at scala.build.Build$.build(Build.scala:597)
	at scala.cli.commands.run.Run$.runCommand(Run.scala:280)
	at scala.cli.commands.run.Run$.runCommand(Run.scala:58)
	at scala.cli.commands.default.Default.runCommand(Default.scala:58)
	at scala.cli.commands.default.Default.runCommand(Default.scala:44)
	at scala.cli.commands.ScalaCommand.run(ScalaCommand.scala:273)
	at scala.cli.commands.ScalaCommand.run(ScalaCommand.scala:266)
	at caseapp.core.app.CaseApp.main(CaseApp.scala:150)
	at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:120)
	at scala.cli.ScalaCliCommands.main(ScalaCliCommands.scala:125)
	at scala.cli.ScalaCli$.main0(ScalaCli.scala:198)
	at scala.cli.ScalaCli$.main(ScalaCli.scala:102)
	at scala.cli.ScalaCli.main(ScalaCli.scala)
```

### PR DESCRIPTION
**Pull request by lwronski**
Fixes #1882.

I reproduced bug from #1882, and now when users run `scala-cli` it print the following error:
```
➜  scala-demo /Users/lwronski/projects/scala-cli/out/cli/standaloneLauncher.dest/launcher Hello.scala 
[E] Failed to load project from /private/tmp/scala-demo/.scala-build/.bloop/project_853f6d1dbb-25fccf1679.json
Something is wrong with the current configuration. Nailgun server failed with exit code 1.
To resolve the problem, please run the clean sub-command to clear the working directory and remove caches.
If the error persists, please report the issue as a bug and attach a log with increased verbosity by passing -v -v -v.
Error: java.lang.RuntimeException: Bloop BSP connection in /Users/lwronski/Library/Caches/ScalaCli/bsp-sockets/proc-91655 was unexpectedly closed or bloop didn't start.
For more details, please see '/private/tmp/scala-demo/.scala-build/stacktraces/1678358545-18379785233871606763.log'
```

### CODE REVIEW

File: modules/bloop-rifle/src/main/scala/scala/build/blooprifle/internal/Operations.scala [hunk 1]
```diff
@@ -349,6 +349,12 @@ object Operations {
           stop0,
           interactiveSession = false
         )
+        if (retCode != 0)
+          logger.error(
+            s"""Something is wrong with the current configuration. Nailgun server failed with exit code $retCode.
+               |To resolve the problem, please run the ${Console.BOLD}clean${Console.RESET} sub-command to clear the working directory and remove caches.
+               |If the error persists, please report the issue as a bug and attach a log with increased verbosity by passing ${Console.BOLD}-v -v -v${Console.RESET}.""".stripMargin)
```
Comment (alexarchambault) [inline modules/bloop-rifle/src/main/scala/scala/build/blooprifle/internal/Operations.scala]: I'd change the phrasing a bit here
```suggestion
            s"""Bloop bsp command exited with code $retCode. Something may be wrong with the current configuration.
               |Running the ${Console.BOLD}clean${Console.RESET} sub-command to clear the working directory and remove caches might help.
               |If the error persists, please report the issue as a bug and attach a log with increased verbosity by passing ${Console.BOLD}-v -v -v${Console.RESET}.""".stripMargin)
```

File: modules/bloop-rifle/src/main/scala/scala/build/blooprifle/internal/Operations.scala [hunk 2]
```diff
@@ -349,6 +349,12 @@ object Operations {
           stop0,
           interactiveSession = false
         )
+        if (retCode != 0)
+          logger.error(
+            s"""Bloop bsp command exited with code $retCode. Something may be wrong with the current configuration.
```
Comment (alexarchambault) [inline modules/bloop-rifle/src/main/scala/scala/build/blooprifle/internal/Operations.scala]: NIT Last small change
```suggestion
            s"""Bloop 'bsp' command exited with code $retCode. Something may be wrong with the current configuration.
```

(This conveys better that the command is `bsp`.)

**Review by alexarchambault — APPROVED** [review]
Apart from the minor extra suggested change, LGTM

File: modules/bloop-rifle/src/main/scala/scala/build/blooprifle/internal/Operations.scala (hunk 2 above)
Comment (lwronski) [reply modules/bloop-rifle/src/main/scala/scala/build/blooprifle/internal/Operations.scala]: Thanks for review!
