### PR TITLE
Fix pgp create with no java 17

### LINKED ISSUE #2035: scala-cli config --create-pgp-key fails when using Java 8
**Version(s)**
`1.0.0-RC1`

**Describe the bug**
When using a pre-installed JDK 8, running `scala-cli config --create-pgp-key` fails with a `ClassNotFoundException` (on my x86_64 Mac at least).

**To Reproduce**
```text
$ java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b09, mixed mode)

$ scala-cli config --create-pgp-key
Exception in thread "main" java.lang.NoClassDefFoundError: java/util/HexFormat
	at scala.cli.signing.commands.PgpCreate$.tryRun(PgpCreate.scala:53)
	at scala.cli.signing.commands.PgpCreate$.run(PgpCreate.scala:23)
	at scala.cli.signing.commands.PgpCreate$.run(PgpCreate.scala:22)
	at caseapp.core.app.CaseApp.main(CaseApp.scala:162)
	at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:115)
	at scala.cli.signing.ScalaCliSigning$.main(ScalaCliSigning.scala:35)
	at scala.cli.signing.ScalaCliSigning.main(ScalaCliSigning.scala)
Caused by: java.lang.ClassNotFoundException: java.util.HexFormat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
[error]  Failed to create PGP key pair (see messages above, scala-cli-signing return code: 1)
```

**Expected behaviour**
That command should succeed in creating a PGP key in the Scala CLI config.

### PR DESCRIPTION
**Pull request by MaciejG604**
Fixes #2035

### CODE REVIEW

File: modules/cli/src/main/scala/scala/cli/commands/publish/checks/PgpSecretKeyCheck.scala [hunk 1]
```diff
@@ -102,7 +102,7 @@ final case class PgpSecretKeyCheck(
       pubKeyOpt match {
         case Some(pubKey) =>
           val keyId = value {
-            (new PgpProxyMaker).get().keyId(
+            (new PgpProxyMaker).get(false).keyId(
```
Comment (lwronski) [inline modules/cli/src/main/scala/scala/cli/commands/publish/checks/PgpSecretKeyCheck.scala]: Instead of passing `false` by default, the value should be extracted from the options, as above from `options.forceSigningExternally`

File: modules/cli/src/main/scala/scala/cli/commands/pgp/PgpExternalCommand.scala [hunk 2]
```diff
@@ -120,14 +123,64 @@ abstract class PgpExternalCommand extends ExternalCommand {
 }
 
 object PgpExternalCommand {
+  val scalaCliSigningJvmVersion: Int = 17
```
Comment (lwronski) [inline modules/cli/src/main/scala/scala/cli/commands/pgp/PgpExternalCommand.scala]: It is better to keep such constant values in `scala.cli.commands.Constants` and hardcoded it in `build.sc`.

File: modules/cli/src/main/scala/scala/cli/commands/pgp/PgpExternalCommand.scala [hunk 3]
```diff
@@ -120,14 +123,64 @@ abstract class PgpExternalCommand extends ExternalCommand {
...
+
+    for {
+      binary <- launcher(
+        cache,
+        archiveCache,
+        logger,
+        javaCommand,
+        signingCliOptions
+      )
+    } yield binary
```
Comment (lwronski) [inline modules/cli/src/main/scala/scala/cli/commands/pgp/PgpExternalCommand.scala]:
```suggestion
   launcher(
        cache,
        archiveCache,
        logger,
        javaCommand,
        signingCliOptions
      )
```

File: modules/cli/src/main/scala/scala/cli/commands/pgp/PgpExternalCommand.scala [hunk 4]
```diff
@@ -120,14 +123,64 @@ abstract class PgpExternalCommand extends ExternalCommand {
...
+
+    for {
+      binary <- launcher(
+        cache,
+        archiveCache,
+        logger,
+        javaCommand,
+        buildOptions.notForBloopOptions.publishOptions.signingCli
+      )
+    } yield binary
```
Comment (lwronski) [inline modules/cli/src/main/scala/scala/cli/commands/pgp/PgpExternalCommand.scala]:
```suggestion
   launcher(
        cache,
        archiveCache,
        logger,
        javaCommand,
        signingCliOptions
      )
```

File: modules/cli/src/main/scala/scala/cli/commands/pgp/PgpScalaSigningOptions.scala [hunk 5]
```diff
@@ -10,16 +10,18 @@ import scala.cli.commands.tags
...
+  @HelpMessage("Pass arguments to the java command when running scala-cli-singing externally on JVM")
   @ValueDescription("option")
   @Hidden
     signingCliJavaArg: List[String] = Nil,
   @Group(HelpGroup.Signing.toString)
   @Tag(tags.restricted)
-  @HelpMessage("Whether to run the Scala Signing CLI on the JVM or using a native executable")
+  @HelpMessage("When using externally run scala-cli-singing, force the use of JVM to execute it")
   @Hidden
     forceJvmSigningCli: Option[Boolean] = None
```
Comment (lwronski) [inline modules/cli/src/main/scala/scala/cli/commands/pgp/PgpScalaSigningOptions.scala:32]: What is the difference between options `forceJvmSigningCli` and  `forceSigningExternally` ? Is it the same?

Comment (MaciejG604) [reply modules/cli/src/main/scala/scala/cli/commands/pgp/PgpScalaSigningOptions.scala:32]: When Scala CLI is run via a JVM runner, then by default PGP operations are done using scala-cli-signing as a dependency, so in this case `forceSigningExternally` forces using scala-cli-signing via an external process.

When Scala CLI is run via a native image, then the default for PGP is to download a native image binary of scala-cli-signing or, if there's no binary for the underlaying architecture, download a jar of scala-cli-signing. In this case `forceSigningExternally` has no effect, but `forceJvmSigningCli` will make the program go straight to downloading the jar file without checking if a native image is available.

So when running on JVM:
- NONE -> use scala-cli-signing as a dependency
- `forceSigningExternally` -> check for native image binary if not present downlaod jar and run it with `java -cp`
- `forceSigningExternally` + `forceJvmSigningCli` -> downlaod jar and run it with `java -cp`

When running as native image:
- NONE -> check for native image binary if not present downlaod jar and run it with `java -cp`
- `forceSigningExternally` -> check for native image binary if not present downlaod jar and run it with `java -cp`
- `forceSigningExternally` + `forceJvmSigningCli` -> downlaod jar and run it with `java -cp`

This took me a while to understand, that's why I'm explaining it in such a verbose way.

Comment (MaciejG604) [reply modules/cli/src/main/scala/scala/cli/commands/pgp/PgpScalaSigningOptions.scala:32]: On the other hand do we really need those options, are there any real use cases for them? Hard to tell

File: modules/cli/src/main/scala/scala/cli/commands/publish/checks/PgpSecretKeyCheck.scala (hunk 1 above)
Comment (lwronski) [reply modules/cli/src/main/scala/scala/cli/commands/publish/checks/PgpSecretKeyCheck.scala]: I don't see that this suggestion is resolved in code.

File: modules/cli/src/main/scala/scala/cli/commands/pgp/PgpPushOptions.scala [hunk 6]
```diff
@@ -25,8 +25,9 @@ final case class PgpPushOptions(
   @HelpMessage("Whether to exit with code 0 if no key is passed")
     allowEmpty: Boolean = false,
   @Group(HelpGroup.PGP.toString)
+  @HelpMessage("When running Scala CLI on the JVM, force running scala-cli-singing externally")
```
Comment (lwronski) [inline modules/cli/src/main/scala/scala/cli/commands/pgp/PgpPushOptions.scala]:
```suggestion
  @HelpMessage("When running the Scala CLI on the JVM, force running scala-cli-singing as a JVM or native launcher")
```

File: modules/cli/src/main/scala/scala/cli/commands/pgp/PgpScalaSigningOptions.scala [hunk 7]
```diff
@@ -10,23 +10,31 @@ import scala.cli.commands.tags
 final case class PgpScalaSigningOptions(
   @Group(HelpGroup.Signing.toString)
   @Tag(tags.restricted)
+  @HelpMessage("Version of scala-cli-signing to use when running it externally")
```
Comment (lwronski) [inline modules/cli/src/main/scala/scala/cli/commands/pgp/PgpScalaSigningOptions.scala]:
```suggestion
  @HelpMessage(s"scala-cli-signing version when running externally (${Constants.scalaCliSigningVersion} by default)")
```

File: modules/cli/src/main/scala/scala/cli/commands/pgp/PgpScalaSigningOptions.scala [hunk 8]
```diff
@@ -10,23 +10,31 @@ import scala.cli.commands.tags
...
   @Hidden
     signingCliVersion: Option[String] = None,
   @Group(HelpGroup.Signing.toString)
   @Tag(tags.restricted)
+  @HelpMessage("Pass arguments to the java command when running scala-cli-singing externally on JVM")
```
Comment (lwronski) [inline modules/cli/src/main/scala/scala/cli/commands/pgp/PgpScalaSigningOptions.scala]:
```suggestion
  @HelpMessage("Pass arguments to the Java command when running scala-cli-singing externally on JVM")
```

File: modules/cli/src/main/scala/scala/cli/commands/pgp/PgpScalaSigningOptions.scala [hunk 9]
```diff
@@ -10,23 +10,31 @@ import scala.cli.commands.tags
...
   @ValueDescription("option")
   @Hidden
     signingCliJavaArg: List[String] = Nil,
   @Group(HelpGroup.Signing.toString)
+  @HelpMessage("When running Scala CLI on the JVM, force running scala-cli-singing externally")
```
Comment (lwronski) [inline modules/cli/src/main/scala/scala/cli/commands/pgp/PgpScalaSigningOptions.scala:24]:
```suggestion
  @HelpMessage("When running the Scala CLI on the JVM, force running scala-cli-singing as a JVM or native launcher")
```

File: modules/cli/src/main/scala/scala/cli/commands/pgp/PgpScalaSigningOptions.scala [hunk 10]
```diff
@@ -10,23 +10,31 @@ import scala.cli.commands.tags
...
+  @Hidden
+  @Tag(tags.restricted)
+    forceSigningExternally: Option[Boolean] = None,
+  @Group(HelpGroup.Signing.toString)
   @Tag(tags.restricted)
-  @HelpMessage("Whether to run the Scala Signing CLI on the JVM or using a native executable")
+  @HelpMessage("When using externally run scala-cli-singing, force the use of JVM to execute it")
```
Comment (lwronski) [inline modules/cli/src/main/scala/scala/cli/commands/pgp/PgpScalaSigningOptions.scala]:
```suggestion
  @HelpMessage("When running scala-cli-singing externally, ensure the use of JVM for its execution")
```

**Review by lwronski — APPROVED** [review]
LGTM
