### PR TITLE
Fix path to sourceMappingURL

### LINKED ISSUE #1235: JS sourceMappingURL is wrong
**Version(s)**
0.1.11

**Describe the bug**
The `sourceMappingURL` doesn't match the name of the sourcemap.

**To Reproduce**
```scala
//> using platform "js"
//> using jsEmitSourceMaps true

@main def whatever = ()
```

```
$ scala-cli --version
0.1.11
$ scala-cli package bug.scala 
Compiling project (Scala 3.1.3, Scala.js)
Compiled project (Scala 3.1.3, Scala.js)
Emitted js source maps to: /workspace/sandbox/whatever.js.map
Wrote /workspace/sandbox/whatever.js, run it with
  node ./whatever.js
gitpod /workspace/sandbox (main) $ ls
bug.scala  README.md  whatever.js  whatever.js.map
$ tail -n 1 whatever.js
//# sourceMappingURL=main.js.map
```

**Expected behaviour**
The `sourceMappingURL` should match the name of the sourcemap.

### PR DESCRIPTION
**Pull request by lwronski**

### CODE REVIEW

File: modules/integration/src/test/scala/scala/cli/integration/PackageTestDefinitions.scala [hunk 1]
```diff
@@ -223,7 +226,14 @@ abstract class PackageTestDefinitions(val scalaVersionOpt: Option[String])
       )
 
       val expectedSourceMapsPath = root / s"$destName.map"
+      val expectedHelloJsPath    = root / destName
+      expect(os.isFile(expectedHelloJsPath))
       expect(os.isFile(expectedSourceMapsPath))
+
+      val jsContent        = os.read(expectedHelloJsPath)
+      val sourceMappingURL = jsContent.split(System.lineSeparator()).toList.lastOption
+      assert(sourceMappingURL.nonEmpty)
```
Comment (Gedochao) [inline modules/integration/src/test/scala/scala/cli/integration/PackageTestDefinitions.scala]: NIT why `assert` and not `expect` here?

**Review by Gedochao — APPROVED** [review]
LGTM
