### PR TITLE
Set workspace dir to `os.tmp.dir` for virtual sources

### LINKED ISSUE #1459: When using process substitution or -e, Scala CLI shouldn't create .scala-build in the current directory
**Version(s)**
`0.1.16`

**Describe the bug**
Running commands such as
```bash
$ scala-cli <(echo 'println("Hello")')
$ scala-cli -e 'println("Hello")'
```
creates a `.scala-build` directory, and uses it to compile the provided input. Scala CLI should rather use a directory under the home directory for that purpose.

### PR DESCRIPTION
**Pull request by lwronski**
Fixes #1459

### CODE REVIEW

File: modules/integration/src/test/scala/scala/cli/integration/RunPipedSourcesTestDefinitions.scala [hunk 1]
```diff
@@ -202,4 +202,14 @@ trait RunPipedSourcesTestDefinitions { _: RunTestDefinitions =>
       expect(output == expectedOutput)
     }
   }
+
+  test("running script snipped should not create workspace dir in cwd") {
```
Comment (Gedochao) [inline modules/integration/src/test/scala/scala/cli/integration/RunPipedSourcesTestDefinitions.scala]:
```suggestion
  test("running a script snippet should not create the workspace dir in cwd") {
```

File: modules/integration/src/test/scala/scala/cli/integration/RunPipedSourcesTestDefinitions.scala [hunk 2]
```diff
@@ -202,4 +202,14 @@ trait RunPipedSourcesTestDefinitions { _: RunTestDefinitions =>
...
+    emptyInputs.fromRoot { root =>
+      os.proc(TestUtil.cli, "-e", """println("Hello")""", extraOptions)
+        .call(cwd = root)
+        .out.trim()
```
Comment (Gedochao) [inline modules/integration/src/test/scala/scala/cli/integration/RunPipedSourcesTestDefinitions.scala]: using the right quotation marks is necessary when passing snippets on Windows
```suggestion
      val quotation = TestUtil.argQuotationMark
      val msg = "Hello"
      val res = os.proc(TestUtil.cli, "-e", s"""println($quotation$msg$quotation")""", extraOptions)        
        .call(cwd = root)
        .out.trim()
      expect(res == msg)
```

File: modules/integration/src/test/scala/scala/cli/integration/RunPipedSourcesTestDefinitions.scala (hunk 1 above)
Comment (Gedochao) [reply modules/integration/src/test/scala/scala/cli/integration/RunPipedSourcesTestDefinitions.scala]: btw. this test should go to either `RunSnippetTestDefinitions` or `DefaultTests`

File: modules/integration/src/test/scala/scala/cli/integration/RunPipedSourcesTestDefinitions.scala [hunk 3]
```diff
@@ -202,4 +202,14 @@ trait RunPipedSourcesTestDefinitions { _: RunTestDefinitions =>
...
+      expect(!os.exists(root / Constants.workspaceDirName))
+    }
+  }
```
Comment (Gedochao) [inline modules/integration/src/test/scala/scala/cli/integration/RunPipedSourcesTestDefinitions.scala]: Also, we could have another test confirming the workspace directory **does** get created in the project folder for mixed virtual and on-disk sources, just to be extra sure.

**Review by Gedochao — APPROVED** [review]
