### PR TITLE
Emit source maps for package command

### LINKED ISSUE #779: jsSourceMaps are not emitted.
**Version(s)**

0.1.2

**Describe the bug**

When told to emit js source maps, scala cli does not

**To Reproduce**

```scala
//> using jsEmitSourceMaps "true"

import org.scalajs.dom
import dom.html


@main def main() = 
  val container = dom.document.querySelector("#container")
  val content = dom.document.createElement("div")
  content.classList.add("content")
  content.textContent = "This is the glorious text-content!"

  container.appendChild(content)
```

`scala-cli package scalajs-file.scala --js --js-emit-source-maps --dependency org.scala-js::scalajs-dom::2.1.0`

No js source maps emitted.

**Expected behaviour**
Source maps should be produced alongside the js file.

### PR DESCRIPTION
**Pull request by lwronski**

### CODE REVIEW

**Review by romanowski — CHANGES_REQUESTED** [review]
I think we should also add information to `--js-emit-source-map` where  source map would be created and how to change it. I think it should also have an entry on JS guide.

Beside that looks ok.

File: modules/cli/src/main/scala/scala/cli/commands/ScalaJsOptions.scala [hunk 1]
```diff
@@ -60,6 +63,7 @@ final case class ScalaJsOptions(
       moduleKindStr = jsModuleKind,
       checkIr = jsCheckIr,
       emitSourceMaps = jsEmitSourceMaps,
+      sourceMapsDest = jsSourceMapsPath.map(os.Path(_, Os.pwd)),
```
Comment (alexarchambault) [inline modules/cli/src/main/scala/scala/cli/commands/ScalaJsOptions.scala]: NIT
```suggestion
      sourceMapsDest = jsSourceMapsPath
        .filter(_.trim.nonEmpty)
        .map(os.Path(_, Os.pwd)),
```

**Review by alexarchambault — COMMENTED** [review]
Don't know for @romanowski's points, but apart from the minor NIT, it's fine by me.

**Review by alexarchambault — APPROVED** [review]
